In [19]:
import torch
import torch.nn as nn
#import torchvision

In [31]:
!pip install torch==1.5.0

In [30]:
torch.__version__

'1.0.1'

In [14]:
!pip install torchvision==0.4.2+cpu -f https://download.pytorch.org/whl/torch_stable.html

Looking in links: https://download.pytorch.org/whl/torch_stable.html
  Using cached https://download.pytorch.org/whl/cpu/torchvision-0.4.2%2Bcpu-cp36-cp36m-win_amd64.whl (751 kB)
  Attempting uninstall: torchvision
    Found existing installation: torchvision 0.1.8
    Uninstalling torchvision-0.1.8:
      Successfully uninstalled torchvision-0.1.8


In [3]:
x=torch.rand(3, requires_grad=True)
print(x)

tensor([0.5963, 0.1926, 0.6496], requires_grad=True)


In [9]:
w=torch.ones(4, requires_grad=True)

for epoch in range(3):
    model_output=(w*3).sum()
    model_output.backward()
    print(model_output)
    print(w.grad)

tensor(12., grad_fn=<SumBackward0>)
tensor([3., 3., 3., 3.])
tensor(12., grad_fn=<SumBackward0>)
tensor([6., 6., 6., 6.])
tensor(12., grad_fn=<SumBackward0>)
tensor([9., 9., 9., 9.])


In [11]:
X = torch.tensor([[1], [2], [3], [4]], dtype=torch.float32)
Y = torch.tensor([[2], [4], [6], [8]], dtype=torch.float32)

n_samples, n_features = X.shape
print(f'#samples: {n_samples}, #features: {n_features}')

#samples: 4, #features: 1


In [15]:
X_test = torch.tensor([5], dtype=torch.float32)
X_test.item()

5.0

In [26]:
import torch
import torch.nn as nn
import numpy as np
from sklearn import datasets
import matplotlib.pyplot as plt

# 0) Prepare data
X_numpy, y_numpy = datasets.make_regression(n_samples=100, n_features=1, noise=20, random_state=4)

In [27]:
X_numpy; X_numpy.dtype # to have the data type

dtype('float64')

In [64]:
X_numpy

array([[-1.3474603 ],
       [ 0.3523434 ],
       [ 0.9546986 ],
       [ 0.03592805],
       [ 0.04800625],
       [ 0.04860301],
       [ 0.72334161],
       [ 0.80208661],
       [-1.14379857],
       [ 0.17941071],
       [-0.64770677],
       [-1.11281215],
       [-1.58457724],
       [-0.08798693],
       [ 2.47658416],
       [-0.7322647 ],
       [ 1.54697933],
       [-0.13070464],
       [ 0.30044554],
       [-0.9443686 ],
       [-0.30296397],
       [-0.37444492],
       [-1.15681626],
       [ 0.59857517],
       [-2.37977527],
       [-0.60768369],
       [ 0.54245131],
       [ 2.02240507],
       [ 0.04613557],
       [ 0.52324766],
       [ 0.29714121],
       [-1.54292905],
       [ 1.69235772],
       [ 0.20931349],
       [-0.41830152],
       [ 0.87084178],
       [-1.14747663],
       [-0.17521053],
       [-0.9617768 ],
       [ 0.1886462 ],
       [ 1.20200259],
       [ 1.99008302],
       [-1.36096559],
       [-0.05455871],
       [ 1.16418756],
       [-1

In [65]:
X = torch.from_numpy(X_numpy.astype(np.float32))
y = torch.from_numpy(y_numpy.astype(np.float32))


In [71]:
len(X)

100

In [68]:
# format changing based on the need in terms of tensor
y = y.view(y.shape[0], 1)
y.shape 

torch.Size([100, 1])

In [69]:
y

tensor([[-126.2492],
        [  50.9288],
        [  63.1546],
        [   6.0547],
        [  -5.7295],
        [  -2.7519],
        [  58.7036],
        [  53.8136],
        [ -95.3411],
        [  24.6481],
        [ -59.4170],
        [ -73.4235],
        [-104.1627],
        [  31.8077],
        [ 171.1535],
        [ -67.7520],
        [ 141.4677],
        [ -24.3676],
        [  -2.1124],
        [ -32.5958],
        [ -29.4151],
        [ -37.8715],
        [-101.8983],
        [  46.4129],
        [-181.3484],
        [ -31.7740],
        [  24.1315],
        [ 163.9438],
        [  10.7737],
        [  37.3589],
        [   0.9804],
        [-120.8857],
        [ 138.1994],
        [   9.2027],
        [ -16.2069],
        [  33.2171],
        [ -45.6170],
        [  -1.7776],
        [-105.5628],
        [   5.2639],
        [  89.5979],
        [ 146.1030],
        [ -77.7870],
        [  -3.8089],
        [  60.8120],
        [ -97.2027],
        [  -1.1599],
        [ -43

In [70]:
n_samples, n_features = X.shape
X.shape
print(n_features)
print(n_samples)

1
100


In [40]:
print(y)

tensor([[-126.2492],
        [  50.9288],
        [  63.1546],
        [   6.0547],
        [  -5.7295],
        [  -2.7519],
        [  58.7036],
        [  53.8136],
        [ -95.3411],
        [  24.6481],
        [ -59.4170],
        [ -73.4235],
        [-104.1627],
        [  31.8077],
        [ 171.1535],
        [ -67.7520],
        [ 141.4677],
        [ -24.3676],
        [  -2.1124],
        [ -32.5958],
        [ -29.4151],
        [ -37.8715],
        [-101.8983],
        [  46.4129],
        [-181.3484],
        [ -31.7740],
        [  24.1315],
        [ 163.9438],
        [  10.7737],
        [  37.3589],
        [   0.9804],
        [-120.8857],
        [ 138.1994],
        [   9.2027],
        [ -16.2069],
        [  33.2171],
        [ -45.6170],
        [  -1.7776],
        [-105.5628],
        [   5.2639],
        [  89.5979],
        [ 146.1030],
        [ -77.7870],
        [  -3.8089],
        [  60.8120],
        [ -97.2027],
        [  -1.1599],
        [ -43

In [23]:
y_numpy.tolist() #important to be considered

[-126.24922408781046,
 50.92876904325736,
 63.154633021922386,
 6.0547200864738375,
 -5.729540250573546,
 -2.7519176884175236,
 58.703559231999456,
 53.81362958288187,
 -95.34105851183199,
 24.64812470939173,
 -59.41697405621463,
 -73.423496188166,
 -104.16266749164922,
 31.80766771985798,
 171.15350154382287,
 -67.75196496665721,
 141.46769810857572,
 -24.367569727471952,
 -2.112400965158713,
 -32.59583109463834,
 -29.415058193041002,
 -37.871459893797656,
 -101.89829600633351,
 46.4128778382706,
 -181.34840043973222,
 -31.773995042999637,
 24.1315487857442,
 163.9438514385304,
 10.773671108563668,
 37.3589153231352,
 0.9803670329602028,
 -120.88573187580702,
 138.19938796923478,
 9.202679031137727,
 -16.206889896630774,
 33.21708479093532,
 -45.61698487997882,
 -1.7775890826236296,
 -105.56283971056314,
 5.263946246750672,
 89.5978923010736,
 146.1030043897126,
 -77.78704394495927,
 -3.8089360671080916,
 60.81195812269342,
 -97.20271029733965,
 -1.1598933445644217,
 -43.8824596382184

# logistic regression (binary classification)

In [72]:

import numpy as np
from sklearn import datasets
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split

bc = datasets.load_breast_cancer()
X, y = bc.data, bc.target

In [76]:
len(X[0])

30

In [74]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=1234)

In [75]:
number_samples, n_features=X.shape
print(number_samples)
print(n_features)

569
30


In [79]:
len(X_train)

455

In [78]:
len(X_test)

114

In [77]:
float(y_test.shape[0])

114.0

In [46]:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0,
       1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0,
       1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0,
       0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1,
       1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0,
       1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0,

# Dataset and dataloader: but it runs while using command prompt based on pyto

# here it shows the error, due to pytorch version 1.0.1

# Check the file:

# C:\Users\2304373.UNIPHOREIND\Pictures\pytorch_tutorial_python_engineer\pytorchTutorial-master\data\pytorch_ex.py

# by running the code in anaconda prompt and navigating to the foldera with executing under environment variable, pyto. it works well try it due to pytorch 1.5.0

In [22]:
print(torch.__version__)

1.0.1


In [21]:
class WineDataset(Dataset):

    def __init__(self):
        # Initialize data, download, etc.
        # read with numpy or pandas
        xy = np.loadtxt('C:\\Users\\2304373.UNIPHOREIND\\Pictures\\pytorch_tutorial_python_engineer\\pytorchTutorial-master\\data\\winewine.csv', delimiter=',', dtype=np.float32, skiprows=1)
        self.n_samples = xy.shape[0]

        # here the first column is the class label, the rest are the features
        self.x_data = torch.from_numpy(xy[:, 1:]) # size [n_samples, n_features]
        self.y_data = torch.from_numpy(xy[:, [0]]) # size [n_samples, 1]

    # support indexing such that dataset[i] can be used to get i-th sample
    def __getitem__(self, index):
        return self.x_data[index], self.y_data[index]

    # we can call len(dataset) to return the size
    def __len__(self):
        return self.n_samples


# create dataset
dataset = WineDataset()

# get first sample and unpack
first_data = dataset[0]
features, labels = first_data
print(features, labels)

NameError: name 'Dataset' is not defined

# nltk check

In [34]:
import nltk

In [122]:
import numpy as np
import nltk
#nltk.download('punkt')
from nltk.stem.porter import PorterStemmer
stemmer = PorterStemmer()

# Checking with dummy data for fully connected layer correctly work first example-python engineer channel

In [253]:
x=torch.rand(60,60).view(1,1,60,60)

In [254]:
conv1 = nn.Conv2d(1, 6, 5)
pool = nn.MaxPool2d(2, 2)
conv2 = nn.Conv2d(6, 16, 5)

In [255]:
x.shape

torch.Size([1, 1, 60, 60])

In [256]:
x=conv1(x)


In [257]:
x.shape

torch.Size([1, 6, 56, 56])

In [258]:
x=pool(x)

In [259]:
x.shape

torch.Size([1, 6, 28, 28])

In [260]:
x=conv2(x)

In [261]:
x.shape

torch.Size([1, 16, 24, 24])

In [240]:
x=pool(x)

In [241]:
x.shape

torch.Size([1, 16, 12, 12])

In [242]:
import torch.nn.functional as F

In [170]:
x=torch.rand(60,60).view(1,1,60,60)
x.shape

torch.Size([1, 1, 60, 60])

# Also we can follow this

In [245]:
#Also we can follow this

x=torch.rand(1,1,60,60)
x.shape

torch.Size([1, 1, 60, 60])

In [182]:
#x = x.reshape(x.shape[0], -1)
#x.shape

In [251]:
#original
class ConvNet(nn.Module):
    def __init__(self):
        super(ConvNet, self).__init__()
        self.conv1 = nn.Conv2d(1, 6, 5)
        self.pool = nn.MaxPool2d(2, 2)
        self.conv2 = nn.Conv2d(6, 16, 5)
        self.fc1 = nn.Linear(16 * 12 * 12, 120)
        self.fc2 = nn.Linear(120, 84)
        self.fc3 = nn.Linear(84, 10)

    def forward(self, x):
        # -> n, 3, 32, 32
        x = self.pool(F.relu(self.conv1(x)))  # -> n, 6, 14, 14
        x = self.pool(F.relu(self.conv2(x)))  # -> n, 16, 5, 5
        x = x.view(-1, 16 * 12 * 12)            # -> n, 400
        x = F.relu(self.fc1(x))               # -> n, 120
        x = F.relu(self.fc2(x))               # -> n, 84
        x = self.fc3(x)                       # -> n, 10
        return x


model = ConvNet()

In [252]:
model(x)

tensor([[ 0.0335,  0.0860,  0.1078, -0.0222,  0.0168,  0.0373,  0.1296,  0.0553,
         -0.0719, -0.0168]], grad_fn=<AddmmBackward>)

# Checking with dummy data for fully connected layer (another example) -sentdex CNN example

In [321]:
x = torch.randn(50,50).view(-1,1,50,50)
x.shape

torch.Size([1, 1, 50, 50])

In [315]:
conv1 = nn.Conv2d(1, 32, 5)
pool = nn.MaxPool2d(2, 2)
conv2 = nn.Conv2d(32, 64, 5)
conv3 = nn.Conv2d(64, 128, 5)

In [316]:
x=conv1(x)
print(x.shape)
x=pool(x)
print(x.shape)
x=conv2(x)
print(x.shape)
x=pool(x)
print(x.shape)
x=conv3(x)
print(x.shape)
x=pool(x)
print(x.shape)

torch.Size([1, 32, 46, 46])
torch.Size([1, 32, 23, 23])
torch.Size([1, 64, 19, 19])
torch.Size([1, 64, 9, 9])
torch.Size([1, 128, 5, 5])
torch.Size([1, 128, 2, 2])


In [317]:
x = torch.randn(50,50).view(-1,1,50,50)
x.shape

torch.Size([1, 1, 50, 50])

In [318]:
class Net(nn.Module):
    def __init__(self):
        super().__init__() # just run the init of parent class (nn.Module)
        self.conv1 = nn.Conv2d(1, 32, 5) # input is 1 image, 32 output channels, 5x5 kernel / window
        self.conv2 = nn.Conv2d(32, 64, 5) # input is 32, bc the first layer output 32. Then we say the output will be 64 channels, 5x5 kernel / window
        self.conv3 = nn.Conv2d(64, 128, 5)

        #self.fc1 = nn.Linear(64*9*9, 512) 2 layers CNN
        self.fc1 = nn.Linear(128*2*2, 512)
        self.fc2 = nn.Linear(512, 2) 
        
    def forward(self, x):
        x = F.max_pool2d(F.relu(self.conv1(x)), (2, 2))
        x = F.max_pool2d(F.relu(self.conv2(x)), (2, 2))
        x = F.max_pool2d(F.relu(self.conv3(x)), (2, 2))
       
        #x = x.view(-1,64*9*9)  2 layers CNN
        x = x.view(-1,128*2*2)
        x = F.relu(self.fc1(x))
        x = self.fc2(x)
        return F.softmax(x, dim=1)

In [319]:
model = Net()

In [320]:
model(x)

tensor([[0.4828, 0.5172]], grad_fn=<SoftmaxBackward>)

In [196]:
len(x)

1

In [215]:
x = torch.randn(50,50)

In [216]:
x=x.view(4,1,25,25) # reshape

In [217]:
x.shape

torch.Size([4, 1, 25, 25])

In [218]:
x.size()

torch.Size([4, 1, 25, 25])

In [76]:
len(x)

1

# Squeeze the dimensions helpful and important in RNN (pytorch)

In [197]:
x=torch.rand(1,1,60,60)
x.shape

torch.Size([1, 1, 60, 60])

In [205]:
x=torch.rand(4,1,28,28)
x.shape

torch.Size([4, 1, 28, 28])

In [212]:
y=torch.squeeze(x,1)

In [213]:
y.shape

torch.Size([4, 28, 28])

# We can also squeeze like this

In [221]:
x=torch.rand(4,1,28,28)
x.shape

torch.Size([4, 1, 28, 28])

In [222]:
y=x.squeeze(1)

In [223]:
y.shape

torch.Size([4, 28, 28])

# Transfer learning-Aladdin Persson

In [276]:
import torch
import torch.nn as nn  # All neural network modules, nn.Linear, nn.Conv2d, BatchNorm, Loss functions

VGG_types = {
    "VGG11": [64, "M", 128, "M", 256, 256, "M", 512, 512, "M", 512, 512, "M"],
    "VGG13": [64, 64, "M", 128, 128, "M", 256, 256, "M", 512, 512, "M", 512, 512, "M"],
    "VGG16": [
        64,
        64,
        "M",
        128,
        128,
        "M",
        256,
        256,
        256,
        "M",
        512,
        512,
        512,
        "M",
        512,
        512,
        512,
        "M",
    ],
    "VGG19": [
        64,
        64,
        "M",
        128,
        128,
        "M",
        256,
        256,
        256,
        256,
        "M",
        512,
        512,
        512,
        512,
        "M",
        512,
        512,
        512,
        512,
        "M",
    ],
}


class VGG_net(nn.Module):
    def __init__(self, in_channels=3, num_classes=1000):
        super(VGG_net, self).__init__()
        self.in_channels = in_channels
        self.conv_layers = self.create_conv_layers(VGG_types["VGG16"])

        self.fcs = nn.Sequential(
            nn.Linear(512 * 7 * 7, 4096),
            nn.ReLU(),
            nn.Dropout(p=0.5),
            nn.Linear(4096, 4096),
            nn.ReLU(),
            nn.Dropout(p=0.5),
            nn.Linear(4096, num_classes),
        )

    def forward(self, x):
        x = self.conv_layers(x)
        print(x.shape)
        x = x.reshape(x.shape[0], -1)
        x = self.fcs(x)
        return x

    def create_conv_layers(self, architecture):
        layers = []
        in_channels = self.in_channels

        for x in architecture:
            if type(x) == int:
                out_channels = x

                layers += [
                    nn.Conv2d(
                        in_channels=in_channels,
                        out_channels=out_channels,
                        kernel_size=(3, 3),
                        stride=(1, 1),
                        padding=(1, 1),
                    ),
                    nn.BatchNorm2d(x),
                    nn.ReLU(),
                ]
                in_channels = x
            elif x == "M":
                layers += [nn.MaxPool2d(kernel_size=(2, 2), stride=(2, 2))]

        return nn.Sequential(*layers)


if __name__ == "__main__":
    device = "cuda" if torch.cuda.is_available() else "cpu"
    model = VGG_net(in_channels=3, num_classes=1000).to(device)
    print(model)
    ## N = 3 (Mini batch size)
    # x = torch.randn(3, 3, 224, 224).to(device)
    # print(model(x).shape)

VGG_net(
  (conv_layers): Sequential(
    (0): Conv2d(3, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (1): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    (2): ReLU()
    (3): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (4): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    (5): ReLU()
    (6): MaxPool2d(kernel_size=(2, 2), stride=(2, 2), padding=0, dilation=1, ceil_mode=False)
    (7): Conv2d(64, 128, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (8): BatchNorm2d(128, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    (9): ReLU()
    (10): Conv2d(128, 128, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (11): BatchNorm2d(128, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    (12): ReLU()
    (13): MaxPool2d(kernel_size=(2, 2), stride=(2, 2), padding=0, dilation=1, ceil_mode=False)
    (14): Conv2d(128, 256, kernel_size=(3, 3),

In [277]:
x = torch.randn(3, 3, 224, 224).to(device)
print(model(x).shape)

torch.Size([3, 512, 7, 7])
torch.Size([3, 1000])


In [339]:
class CNN(nn.Module):
    def __init__(self, in_channels=1, num_classes=10):
        super(CNN, self).__init__()
        self.conv1 = nn.Conv2d(
            in_channels=1,
            out_channels=8,
            kernel_size=(3, 3),
            stride=(1, 1),
            padding=(1, 1),
        )
        self.pool = nn.MaxPool2d(kernel_size=(2, 2), stride=(2, 2))
        self.conv2 = nn.Conv2d(
            in_channels=8,
            out_channels=16,
            kernel_size=(3, 3),
            stride=(1, 1),
            padding=(1, 1),
        )
        self.fc1 = nn.Linear(16 * 56 * 56, num_classes)

    def forward(self, x):
        x = F.relu(self.conv1(x))
        x = self.pool(x)
        x = F.relu(self.conv2(x))
        x = self.pool(x)
        print(x.shape)
        x = x.reshape(x.shape[0], -1)
        x = self.fc1(x)

        return x


In [340]:
model = CNN().to(device)

In [ ]:
# Based on MNIST dataset check
x = torch.randn(1, 1, 28, 28).to(device)
print(model(x).shape)

In [341]:
x = torch.randn(1, 1, 224, 224).to(device)
print(x.shape)
print(model(x).shape)

torch.Size([1, 1, 224, 224])
torch.Size([1, 16, 56, 56])
torch.Size([1, 10])


# python Engineer channel easy trick

In [342]:
class ConvNet(nn.Module):
    def __init__(self):
        super(ConvNet, self).__init__()
        self.conv1 = nn.Conv2d(1, 6, 5)
        self.pool = nn.MaxPool2d(2, 2)
        self.conv2 = nn.Conv2d(6, 16, 5)
        self.fc1 = nn.Linear(16*12*12, 120)
        self.fc2 = nn.Linear(120, 84)
        self.fc3 = nn.Linear(84, 10)

    def forward(self, x):
        
        x = self.pool(F.relu(self.conv1(x)))  
        x = self.pool(F.relu(self.conv2(x)))
        print(x.shape)
        x = x.view(-1, 16*12*12)            
        x = F.relu(self.fc1(x))              
        x = F.relu(self.fc2(x))               
        x = self.fc3(x)                      
        return x


model = ConvNet()

In [344]:
x = torch.randn(1, 1, 60, 60).to(device)
print(x.shape)
print(model(x).shape)

torch.Size([1, 1, 60, 60])
torch.Size([1, 16, 12, 12])
torch.Size([1, 10])
