In [114]:
from sklearn import svm, datasets
iris = datasets.load_iris()

In [115]:
import pandas as pd
df = pd.DataFrame(iris.data,columns=iris.feature_names)
df['flower'] = iris.target
df['flower'] = df['flower'].apply(lambda x: iris.target_names[x])
df[47:150]

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
47                 4.6               3.2                1.4               0.2   
48                 5.3               3.7                1.5               0.2   
49                 5.0               3.3                1.4               0.2   
50                 7.0               3.2                4.7               1.4   
51                 6.4               3.2                4.5               1.5   
..                 ...               ...                ...               ...   
145                6.7               3.0                5.2               2.3   
146                6.3               2.5                5.0               1.9   
147                6.5               3.0                5.2               2.0   
148                6.2               3.4                5.4               2.3   
149                5.9               3.0                5.1               1.8   

         flower  
47       setosa  
48       setosa  
49       setosa  
50   versicolor  
51   versicolor  
..          ...  
145   virginica  
146   virginica  
147   virginica  
148   virginica  
149   virginica  

[103 rows x 5 columns]

In [116]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(iris.data, iris.target, test_size=0.3,random_state=42)

In [117]:
from sklearn.ensemble import RandomForestClassifier

from sklearn.model_selection import GridSearchCV

In [118]:
model_params = {
    
    'random_forest': {
        'model': RandomForestClassifier(),
        'params' : {
            'n_estimators': [1,2,5,10],
            # Maximum number of levels in tree
            'max_depth': [2,4],
            # Minimum number of samples required to split a node
            'min_samples_split': [2, 5],
            # Minimum number of samples required at each leaf node
            'min_samples_leaf':[1, 2],
            # Method of selecting samples for training each tree
            'bootstrap': [True]
        }
    }
    
}

In [119]:
model_params.items()

dict_items([('random_forest', {'model': RandomForestClassifier(), 'params': {'n_estimators': [1, 2, 5, 10], 'max_depth': [2, 4], 'min_samples_split': [2, 5], 'min_samples_leaf': [1, 2], 'bootstrap': [True]}})])

In [120]:
scores = []

for model_name, mp in model_params.items():
    clf =  GridSearchCV(mp['model'], mp['params'], cv=5, return_train_score=False)
    clf.fit(iris.data, iris.target)
    scores.append({
        'model': model_name,
        'best_score': clf.best_score_,
        'best_params': clf.best_params_
    })
    
df = pd.DataFrame(scores,columns=['model','best_score','best_params'])
df

model  best_score  \
0  random_forest    0.966667   

                                         best_params  
0  {'bootstrap': True, 'max_depth': 4, 'min_sampl...

In [121]:
clf.cv_results_

{'mean_fit_time': array([0.00780582, 0.01967335, 0.01840038, 0.03379464, 0.00416474,
        0.00683088, 0.01420836, 0.03038158, 0.0041995 , 0.0070291 ,
        0.01638989, 0.03120923, 0.00394168, 0.00820336, 0.01566362,
        0.02900076, 0.00440269, 0.00760694, 0.0165997 , 0.0291925 ,
        0.00400987, 0.00694771, 0.01579542, 0.03084593, 0.00397425,
        0.00696769, 0.01522737, 0.02816539, 0.00416231, 0.00703278,
        0.01646032, 0.02840314]),
 'std_fit_time': array([1.30652621e-03, 9.58425056e-03, 4.85848400e-03, 9.57053675e-03,
        3.29831864e-04, 3.38173854e-04, 1.15604811e-03, 1.05271913e-03,
        4.47464126e-04, 6.13075552e-04, 1.45115883e-03, 3.50712257e-03,
        5.88026249e-04, 1.12920489e-03, 1.29864225e-03, 1.27640554e-03,
        4.75466700e-04, 8.11925927e-04, 2.80055140e-03, 9.91459714e-04,
        3.13182928e-05, 6.40963320e-04, 7.26274922e-04, 9.42430366e-04,
        3.55544059e-05, 6.31976458e-04, 9.92435833e-04, 7.55851971e-04,
        6.44408363e-0

In [122]:
df = pd.DataFrame(clf.cv_results_)
df

mean_fit_time  std_fit_time  mean_score_time  std_score_time  \
0        0.007806      0.001307         0.001974    3.119055e-05   
1        0.019673      0.009584         0.002312    7.538399e-04   
2        0.018400      0.004858         0.002655    7.478803e-04   
3        0.033795      0.009571         0.003211    9.320742e-04   
4        0.004165      0.000330         0.001000    2.780415e-07   
5        0.006831      0.000338         0.001772    4.623762e-04   
6        0.014208      0.001156         0.002250    7.852241e-04   
7        0.030382      0.001053         0.003207    4.157345e-04   
8        0.004200      0.000447         0.000981    3.794060e-05   
9        0.007029      0.000613         0.001434    4.382818e-04   
10       0.016390      0.001451         0.002409    7.209932e-04   
11       0.031209      0.003507         0.003251    3.998358e-04   
12       0.003942      0.000588         0.001202    4.001506e-04   
13       0.008203      0.001129         0.001575    5.230229e-04   
14       0.015664      0.001299         0.002136    4.354287e-04   
15       0.029001      0.001276         0.002804    4.132248e-04   
16       0.004403      0.000475         0.001050    8.784120e-05   
17       0.007607      0.000812         0.001841    7.317394e-04   
18       0.016600      0.002801         0.002198    4.030515e-04   
19       0.029192      0.000991         0.003030    6.529119e-04   
20       0.004010      0.000031         0.001384    5.041560e-04   
21       0.006948      0.000641         0.001638    4.684635e-04   
22       0.015795      0.000726         0.002406    5.031613e-04   
23       0.030846      0.000942         0.003218    4.438213e-04   
24       0.003974      0.000036         0.001408    4.993921e-04   
25       0.006968      0.000632         0.001401    4.887948e-04   
26       0.015227      0.000992         0.002182    4.121622e-04   
27       0.028165      0.000756         0.003047    6.107827e-04   
28       0.004162      0.000644         0.001605    5.249870e-04   
29       0.007033      0.000609         0.001390    5.445609e-04   
30       0.016460      0.000994         0.002188    3.506108e-04   
31       0.028403      0.000492         0.002983    1.703357e-05   

   param_bootstrap param_max_depth param_min_samples_leaf  \
0             True               2                      1   
1             True               2                      1   
2             True               2                      1   
3             True               2                      1   
4             True               2                      1   
5             True               2                      1   
6             True               2                      1   
7             True               2                      1   
8             True               2                      2   
9             True               2                      2   
10            True               2                      2   
11            True               2                      2   
12            True               2                      2   
13            True               2                      2   
14            True               2                      2   
15            True               2                      2   
16            True               4                      1   
17            True               4                      1   
18            True               4                      1   
19            True               4                      1   
20            True               4                      1   
21            True               4                      1   
22            True               4                      1   
23            True               4                      1   
24            True               4                      2   
25            True               4                      2   
26            True               4                      2   
27            True               4                 

In [123]:
df[['params','mean_test_score']]

params  mean_test_score
0   {'bootstrap': True, 'max_depth': 2, 'min_sampl...         0.840000
1   {'bootstrap': True, 'max_depth': 2, 'min_sampl...         0.946667
2   {'bootstrap': True, 'max_depth': 2, 'min_sampl...         0.940000
3   {'bootstrap': True, 'max_depth': 2, 'min_sampl...         0.960000
4   {'bootstrap': True, 'max_depth': 2, 'min_sampl...         0.953333
5   {'bootstrap': True, 'max_depth': 2, 'min_sampl...         0.946667
6   {'bootstrap': True, 'max_depth': 2, 'min_sampl...         0.953333
7   {'bootstrap': True, 'max_depth': 2, 'min_sampl...         0.953333
8   {'bootstrap': True, 'max_depth': 2, 'min_sampl...         0.900000
9   {'bootstrap': True, 'max_depth': 2, 'min_sampl...         0.933333
10  {'bootstrap': True, 'max_depth': 2, 'min_sampl...         0.946667
11  {'bootstrap': True, 'max_depth': 2, 'min_sampl...         0.953333
12  {'bootstrap': True, 'max_depth': 2, 'min_sampl...         0.880000
13  {'bootstrap': True, 'max_depth': 2, 'min_sampl...         0.940000
14  {'bootstrap': True, 'max_depth': 2, 'min_sampl...         0.953333
15  {'bootstrap': True, 'max_depth': 2, 'min_sampl...         0.953333
16  {'bootstrap': True, 'max_depth': 4, 'min_sampl...         0.933333
17  {'bootstrap': True, 'max_depth': 4, 'min_sampl...         0.940000
18  {'bootstrap': True, 'max_depth': 4, 'min_sampl...         0.953333
19  {'bootstrap': True, 'max_depth': 4, 'min_sampl...         0.966667
20  {'bootstrap': True, 'max_depth': 4, 'min_sampl...         0.940000
21  {'bootstrap': True, 'max_depth': 4, 'min_sampl...         0.946667
22  {'bootstrap': True, 'max_depth': 4, 'min_sampl...         0.966667
23  {'bootstrap': True, 'max_depth': 4, 'min_sampl...         0.966667
24  {'bootstrap': True, 'max_depth': 4, 'min_sampl...         0.940000
25  {'bootstrap': True, 'max_depth': 4, 'min_sampl...         0.946667
26  {'bootstrap': True, 'max_depth': 4, 'min_sampl...         0.966667
27  {'bootstrap': True, 'max_depth': 4, 'min_sampl...         0.966667
28  {'bootstrap': True, 'max_depth': 4, 'min_sampl...         0.960000
29  {'bootstrap': True, 'max_depth': 4, 'min_sampl...         0.946667
30  {'bootstrap': True, 'max_depth': 4, 'min_sampl...         0.960000
31  {'bootstrap': True, 'max_depth': 4, 'min_sampl...         0.953333

In [124]:
clf.best_params_

{'bootstrap': True,
 'max_depth': 4,
 'min_samples_leaf': 1,
 'min_samples_split': 2,
 'n_estimators': 10}

In [135]:
clf.best_score_


0.9666666666666668

In [125]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(iris.data, iris.target, test_size=0.3,random_state=42)

In [126]:
import numpy as np

In [127]:
# Number of trees in random forest
n_estimators = [int(x) for x in np.linspace(start = 10, stop = 80, num = 10)]
# Number of features to consider at every split
max_features = ['auto', 'sqrt']
# Maximum number of levels in tree
max_depth = [2,4]
# Minimum number of samples required to split a node
min_samples_split = [2, 5]
# Minimum number of samples required at each leaf node
min_samples_leaf = [1, 2]
# Method of selecting samples for training each tree
bootstrap = [True, False]


In [128]:
# Create the param grid
param_grid = {'n_estimators': n_estimators,
               'max_features': max_features,
               'max_depth': max_depth,
               'min_samples_split': min_samples_split,
               'min_samples_leaf': min_samples_leaf,
               'bootstrap': bootstrap}
print(param_grid)

{'n_estimators': [10, 17, 25, 33, 41, 48, 56, 64, 72, 80], 'max_features': ['auto', 'sqrt'], 'max_depth': [2, 4], 'min_samples_split': [2, 5], 'min_samples_leaf': [1, 2], 'bootstrap': [True, False]}


In [129]:
rf_Model = RandomForestClassifier()

In [130]:
from sklearn.model_selection import GridSearchCV
rf_Grid = GridSearchCV(estimator = rf_Model, param_grid = param_grid, cv = 3, verbose=2, n_jobs = 4)

In [131]:
rf_Grid.fit(iris.data, iris.target)

Fitting 3 folds for each of 320 candidates, totalling 960 fits


[Parallel(n_jobs=4)]: Using backend LokyBackend with 4 concurrent workers.
[Parallel(n_jobs=4)]: Done  33 tasks      | elapsed:    9.2s
[Parallel(n_jobs=4)]: Done 154 tasks      | elapsed:   17.8s
[Parallel(n_jobs=4)]: Done 357 tasks      | elapsed:   30.9s
[Parallel(n_jobs=4)]: Done 640 tasks      | elapsed:   46.7s
[Parallel(n_jobs=4)]: Done 960 out of 960 | elapsed:  1.1min finished


GridSearchCV(cv=3, estimator=RandomForestClassifier(), n_jobs=4,
             param_grid={'bootstrap': [True, False], 'max_depth': [2, 4],
                         'max_features': ['auto', 'sqrt'],
                         'min_samples_leaf': [1, 2],
                         'min_samples_split': [2, 5],
                         'n_estimators': [10, 17, 25, 33, 41, 48, 56, 64, 72,
                                          80]},
             verbose=2)

In [133]:
df = pd.DataFrame(rf_Grid.cv_results_)
df

mean_fit_time  std_fit_time  mean_score_time  std_score_time  \
0         0.066801      0.019123         0.007956        0.000803   
1         0.106919      0.006440         0.012700        0.004537   
2         0.136090      0.004257         0.009592        0.002041   
3         0.167302      0.008768         0.011362        0.000907   
4         0.194096      0.004454         0.018897        0.008308   
..             ...           ...              ...             ...   
315       0.334487      0.021566         0.023676        0.003869   
316       0.311667      0.037982         0.023666        0.005440   
317       0.293036      0.011176         0.056029        0.026243   
318       0.468322      0.039346         0.036647        0.005754   
319       0.444358      0.016844         0.032840        0.009594   

    param_bootstrap param_max_depth param_max_features param_min_samples_leaf  \
0              True               2               auto                      1   
1              True               2               auto                      1   
2              True               2               auto                      1   
3              True               2               auto                      1   
4              True               2               auto                      1   
..              ...             ...                ...                    ...   
315           False               4               sqrt                      2   
316           False               4               sqrt                      2   
317           False               4               sqrt                      2   
318           False               4               sqrt                      2   
319           False               4               sqrt                      2   

    param_min_samples_split param_n_estimators  \
0                         2                 10   
1                         2                 17   
2                         2                 25   
3                         2                 33   
4                         2                 41   
..                      ...                ...   
315                       5                 48   
316                       5                 56   
317                       5                 64   
318                       5                 72   
319                       5                 80   

                                                params  split0_test_score  \
0    {'bootstrap': True, 'max_depth': 2, 'max_featu...               0.96   
1    {'bootstrap': True, 'max_depth': 2, 'max_featu...               0.96   
2    {'bootstrap': True, 'max_depth': 2, 'max_featu...               0.98   
3    {'bootstrap': True, 'max_depth': 2, 'max_featu...               0.98   
4    {'bootstrap': True, 'max_depth': 2, 'max_featu...               0.96   
..                                                 ...                ...   
315  {'bootstrap': False, 'max_depth': 4, 'max_feat...               0.98   
316  {'bootstrap': False, 'max_depth': 4, 'max_feat...               0.98   
317  {'bootstrap': False, 'max_depth': 4, 'max_feat...               0.98   
318  {'bootstrap': False, 'max_depth': 4, 'max_feat...               0.98   
319  {'bootstrap': False, 'max_depth': 4, 'max_feat...               0.98   

     split1_test_score  split2_test_score  mean_test_score  std_test_score  \
0                 0.92               0.96         0.946667        0.018856   
1                 0.96               0.96         0.960000        0.000000   
2                 0.96               0.96         0.966667        0.009428   
3                 0.92               0.94         0.946667        0.024944   
4                 0.96               0.94         0.953333        0.009428   
..                 ...                ...              ...             ...   
315               0.94               0.94         0.953333        0.018856   
316               0.94               0.92         0.9

In [136]:
rf_Grid.best_score_

0.9733333333333333

In [134]:
rf_Grid.best_params_

{'bootstrap': True,
 'max_depth': 2,
 'max_features': 'auto',
 'min_samples_leaf': 1,
 'min_samples_split': 5,
 'n_estimators': 10}

# Confusion matrix computed based on best params without using common Randomforest and it is useful in our experiments
# or we can try both the approach

In [101]:
from sklearn.metrics import accuracy_score
y_pred=rf_Grid.predict(X_test)
print(confusion_matrix(y_test,y_pred))
print("Accuracy Score {}".format(accuracy_score(y_test,y_pred)))
print("Classification report: {}".format(classification_report(y_test,y_pred)))

[[19  0  0]
 [ 0 13  0]
 [ 0  0 13]]
Accuracy Score 1.0
Classification report:               precision    recall  f1-score   support

           0       1.00      1.00      1.00        19
           1       1.00      1.00      1.00        13
           2       1.00      1.00      1.00        13

    accuracy                           1.00        45
   macro avg       1.00      1.00      1.00        45
weighted avg       1.00      1.00      1.00        45



In [93]:
rf_Grid.get_params()

{'cv': 3,
 'error_score': nan,
 'estimator__bootstrap': True,
 'estimator__ccp_alpha': 0.0,
 'estimator__class_weight': None,
 'estimator__criterion': 'gini',
 'estimator__max_depth': None,
 'estimator__max_features': 'auto',
 'estimator__max_leaf_nodes': None,
 'estimator__max_samples': None,
 'estimator__min_impurity_decrease': 0.0,
 'estimator__min_impurity_split': None,
 'estimator__min_samples_leaf': 1,
 'estimator__min_samples_split': 2,
 'estimator__min_weight_fraction_leaf': 0.0,
 'estimator__n_estimators': 100,
 'estimator__n_jobs': None,
 'estimator__oob_score': False,
 'estimator__random_state': None,
 'estimator__verbose': 0,
 'estimator__warm_start': False,
 'estimator': RandomForestClassifier(),
 'iid': 'deprecated',
 'n_jobs': 4,
 'param_grid': {'n_estimators': [10, 17, 25, 33, 41, 48, 56, 64, 72, 80],
  'max_features': ['auto', 'sqrt'],
  'max_depth': [2, 4],
  'min_samples_split': [2, 5],
  'min_samples_leaf': [1, 2],
  'bootstrap': [True, False]},
 'pre_dispatch': '2*

In [94]:
print (f'Train Accuracy - : {rf_Grid.score(X_train,y_train):.3f}')
print (f'Test Accuracy - : {rf_Grid.score(X_test,y_test):.3f}')

Train Accuracy - : 0.962
Test Accuracy - : 1.000


In [97]:
rf_Grid.best_params_

{'bootstrap': True,
 'max_depth': 2,
 'max_features': 'auto',
 'min_samples_leaf': 1,
 'min_samples_split': 2,
 'n_estimators': 17}

# Confusion matrix based on the above best parameter and tried over normal random forest

In [96]:
from sklearn.metrics import confusion_matrix,classification_report,accuracy_score

In [98]:
model=RandomForestClassifier(n_estimators=17,criterion='gini',max_features='auto',min_samples_leaf=1,min_samples_split=2,max_depth= 2,bootstrap= True).fit(X_train,y_train)
predictions=model.predict(X_test)
print(model.score(X_train,y_train))
print(confusion_matrix(y_test,predictions))
print(accuracy_score(y_test,predictions))
print(classification_report(y_test,predictions))

0.9333333333333333
[[19  0  0]
 [ 0 13  0]
 [ 0  0 13]]
1.0
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        19
           1       1.00      1.00      1.00        13
           2       1.00      1.00      1.00        13

    accuracy                           1.00        45
   macro avg       1.00      1.00      1.00        45
weighted avg       1.00      1.00      1.00        45



# Cross validation analysis (SVM hyperparameters) and it is useful in our experiments

In [138]:
from sklearn.model_selection import cross_val_score

In [139]:
kernels = ['rbf', 'linear']
C = [1,10,20]
avg_scores = {}
for kval in kernels:
    for cval in C:
        cv_scores = cross_val_score(svm.SVC(kernel=kval,C=cval,gamma='auto'),iris.data, iris.target, cv=5)
        avg_scores[kval + '_' + str(cval)] = np.average(cv_scores)

avg_scores


{'rbf_1': 0.9800000000000001,
 'rbf_10': 0.9800000000000001,
 'rbf_20': 0.9666666666666668,
 'linear_1': 0.9800000000000001,
 'linear_10': 0.9733333333333334,
 'linear_20': 0.9666666666666666}

In [140]:
from sklearn.model_selection import GridSearchCV
clf = GridSearchCV(svm.SVC(gamma='auto'), {
    'C': [1,10,20],
    'kernel': ['rbf','linear']
}, cv=5, return_train_score=False)
clf.fit(iris.data, iris.target)
clf.cv_results_

{'mean_fit_time': array([0.00153189, 0.00100198, 0.00138278, 0.00232916, 0.00235806,
        0.00159912]),
 'std_fit_time': array([4.50689985e-04, 3.60509075e-06, 5.00948956e-04, 3.72971235e-04,
        1.03963904e-03, 8.01111990e-04]),
 'mean_score_time': array([0.00039988, 0.00043006, 0.00060325, 0.00169697, 0.00124822,
        0.00186524]),
 'std_score_time': array([0.00048975, 0.00052856, 0.00049257, 0.00083774, 0.00038129,
        0.00073396]),
 'param_C': masked_array(data=[1, 1, 10, 10, 20, 20],
              mask=[False, False, False, False, False, False],
        fill_value='?',
             dtype=object),
 'param_kernel': masked_array(data=['rbf', 'linear', 'rbf', 'linear', 'rbf', 'linear'],
              mask=[False, False, False, False, False, False],
        fill_value='?',
             dtype=object),
 'params': [{'C': 1, 'kernel': 'rbf'},
  {'C': 1, 'kernel': 'linear'},
  {'C': 10, 'kernel': 'rbf'},
  {'C': 10, 'kernel': 'linear'},
  {'C': 20, 'kernel': 'rbf'},
  {'C': 20

In [141]:
df = pd.DataFrame(clf.cv_results_)
df

mean_fit_time  std_fit_time  mean_score_time  std_score_time param_C  \
0       0.001532      0.000451         0.000400        0.000490       1   
1       0.001002      0.000004         0.000430        0.000529       1   
2       0.001383      0.000501         0.000603        0.000493      10   
3       0.002329      0.000373         0.001697        0.000838      10   
4       0.002358      0.001040         0.001248        0.000381      20   
5       0.001599      0.000801         0.001865        0.000734      20   

  param_kernel                         params  split0_test_score  \
0          rbf      {'C': 1, 'kernel': 'rbf'}           0.966667   
1       linear   {'C': 1, 'kernel': 'linear'}           0.966667   
2          rbf     {'C': 10, 'kernel': 'rbf'}           0.966667   
3       linear  {'C': 10, 'kernel': 'linear'}           1.000000   
4          rbf     {'C': 20, 'kernel': 'rbf'}           0.966667   
5       linear  {'C': 20, 'kernel': 'linear'}           1.000000   

   split1_test_score  split2_test_score  split3_test_score  split4_test_score  \
0                1.0           0.966667           0.966667                1.0   
1                1.0           0.966667           0.966667                1.0   
2                1.0           0.966667           0.966667                1.0   
3                1.0           0.900000           0.966667                1.0   
4                1.0           0.900000           0.966667                1.0   
5                1.0           0.900000           0.933333                1.0   

   mean_test_score  std_test_score  rank_test_score  
0         0.980000        0.016330                1  
1         0.980000        0.016330                1  
2         0.980000        0.016330                1  
3         0.973333        0.038873                4  
4         0.966667        0.036515                5  
5         0.966667        0.042164                6

In [142]:
df[['param_C','param_kernel','mean_test_score']]

param_C param_kernel  mean_test_score
0       1          rbf         0.980000
1       1       linear         0.980000
2      10          rbf         0.980000
3      10       linear         0.973333
4      20          rbf         0.966667
5      20       linear         0.966667

In [143]:
clf.best_params_

{'C': 1, 'kernel': 'rbf'}

In [144]:
clf.best_score_

0.9800000000000001

In [145]:
from sklearn.model_selection import RandomizedSearchCV
rs = RandomizedSearchCV(svm.SVC(gamma='auto'), {
        'C': [1,10,20],
        'kernel': ['rbf','linear']
    }, 
    cv=5, 
    return_train_score=False, 
    n_iter=2
)
rs.fit(iris.data, iris.target)
pd.DataFrame(rs.cv_results_)[['param_C','param_kernel','mean_test_score']]

param_C param_kernel  mean_test_score
0       1       linear         0.980000
1      20          rbf         0.966667