In [2]:
import pandas as pd
import numpy as np

In [3]:
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_extraction import DictVectorizer

In [4]:
# Load our data
df = pd.read_csv('C:\\Users\\Venkatesan R\\Pictures\\NLPexperiments\\Python-Machine-Learning-master\\Python-Machine-Learning-master\\Gender Classification With  Machine Learning\\names_dataset.csv')

In [ ]:
print('Default GPU Device: {}'.format(tf.test.gpu_device_name()))

In [5]:
df.head()

index       name sex
0      0       Mary   F
1      1       Anna   F
2      2       Emma   F
3      3  Elizabeth   F
4      4     Minnie   F

In [7]:
df.shape

(95025, 3)

In [9]:
len(df)
#df.size

95025

In [10]:
df.columns

Index(['index', 'name', 'sex'], dtype='object')

In [11]:
# Data Types
df.dtypes

index     int64
name     object
sex      object
dtype: object

In [12]:
# Checking for Missing Values
df.isnull().isnull().sum()

index    0
name     0
sex      0
dtype: int64

In [13]:
df

index       name sex
0            0       Mary   F
1            1       Anna   F
2            2       Emma   F
3            3  Elizabeth   F
4            4     Minnie   F
5            5   Margaret   F
6            6        Ida   F
7            7      Alice   F
8            8     Bertha   F
9            9      Sarah   F
10          10      Annie   F
11          11      Clara   F
12          12       Ella   F
13          13   Florence   F
14          14       Cora   F
15          15     Martha   F
16          16      Laura   F
17          17     Nellie   F
18          18      Grace   F
19          19     Carrie   F
20          20      Maude   F
21          21      Mabel   F
22          22     Bessie   F
23          23     Jennie   F
24          24   Gertrude   F
25          25      Julia   F
26          26     Hattie   F
27          27      Edith   F
28          28     Mattie   F
29          29       Rose   F
...        ...        ...  ..
94995  1858537     Vahagn   M
94996  1858544     Vegeta   M
94997  1858551    Vidhaan   M
94998  1858557    Viransh   M
94999  1858558      Vishv   M
95000  1858561     Waaris   M
95001  1858575      Xaire   M
95002  1858577    Xannder   M
95003  1858588   Yahushua   M
95004  1858590    Yaidden   M
95005  1858591  Yamajesty   M
95006  1858594     Yandry   M
95007  1858595     Yannai   M
95008  1858604      Yiddy   M
95009  1858605       Yien   M
95010  1858610   Yirmeyah   M
95011  1858615   Yordanny   M
95012  1858618   Yoshiyah   M
95013  1858623      Yurik   M
95014  1858625        Ywa   M
95015  1858635      Zafer   M
95016  1858639     Zaheen   M
95017  1858652      Zarar   M
95018  1858654     Zareon   M
95019  1858655    Zarrien   M
95020  1858664   Zecharya   M
95021  1858676     Ziheng   M
95022  1858679       Ziyu   M
95023  1858686      Zykir   M
95024  1858688       Zyus   M

[95025 rows x 3 columns]

In [14]:
# Number of Female Names
df[df.sex == 'F'].size

181800

In [15]:
# Number of Male Names
df[df.sex == 'M'].size

103275

In [16]:
df_names = df

In [17]:
# Replacing All F and M with 0 and 1 respectively
df_names.sex.replace({'F':0,'M':1},inplace=True)

In [18]:
Xfeatures =df_names['name']

In [19]:
# Feature Extraction 
cv = CountVectorizer()
X = cv.fit_transform(Xfeatures) #which is want to be trained should be transformed

In [20]:
from sklearn.model_selection import train_test_split

In [21]:
# Features 
X
# Labels
y = df_names.sex

In [23]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

In [24]:
# Naive Bayes Classifier
from sklearn.naive_bayes import MultinomialNB
clf = MultinomialNB() # clf refers to classifier
clf.fit(X_train,y_train)
clf.score(X_test,y_test)

0.6398163206734908

In [34]:
# Sample1 Prediction
sample_name = ["Mary"]
vect = cv.transform(sample_name).toarray() #tranformed can be processed by toarray

In [35]:
vect

array([[0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [36]:
# Female is 0, Male is 1
clf.predict(vect)

array([0], dtype=int64)

In [37]:
# Sample2 Prediction
sample_name1 = ["Mark"]
vect1 = cv.transform(sample_name1).toarray()

In [38]:
clf.predict(vect1)

array([1], dtype=int64)

In [39]:
# Sample3 Prediction of Russian Names
sample_name2 = ["Natasha"]
vect2 = cv.transform(sample_name2).toarray()

In [40]:
clf.predict(vect2)

array([0], dtype=int64)

In [41]:
# Sample3 Prediction of Random Names
sample_name3 = ["Nefertiti","Nasha","Ama","Ayo","Xhavier","Ovetta","Tathiana","Xia","Joseph","Xianliang"]
vect3 = cv.transform(sample_name3).toarray()

In [42]:
clf.predict(vect3)

array([0, 0, 0, 0, 1, 0, 0, 0, 0, 0], dtype=int64)

In [43]:
# A function to do it
def genderpredictor(a):
    test_name = [a]
    vector = cv.transform(test_name).toarray()
    if clf.predict(vector) == 0:
        print("Female")
    else:
        print("Male")

In [44]:
genderpredictor("Martha")

Female


In [45]:
# By Analogy most female names ends in 'A' or 'E' or has the sound of 'A'
def features(name):
    name = name.lower()
    return {
        'first-letter': name[0], # First letter
        'first2-letters': name[0:2], # First 2 letters
        'first3-letters': name[0:3], # First 3 letters
        'last-letter': name[-1],
        'last2-letters': name[-2:], #minus defines always from last
        'last3-letters': name[-3:],
    }

In [46]:
# Vectorize the features function
features = np.vectorize(features)
print(features(["Anna", "Hannah", "Peter","John","Vladmir","Mohammed"]))

[{'first-letter': 'a', 'first2-letters': 'an', 'first3-letters': 'ann', 'last-letter': 'a', 'last2-letters': 'na', 'last3-letters': 'nna'}
 {'first-letter': 'h', 'first2-letters': 'ha', 'first3-letters': 'han', 'last-letter': 'h', 'last2-letters': 'ah', 'last3-letters': 'nah'}
 {'first-letter': 'p', 'first2-letters': 'pe', 'first3-letters': 'pet', 'last-letter': 'r', 'last2-letters': 'er', 'last3-letters': 'ter'}
 {'first-letter': 'j', 'first2-letters': 'jo', 'first3-letters': 'joh', 'last-letter': 'n', 'last2-letters': 'hn', 'last3-letters': 'ohn'}
 {'first-letter': 'v', 'first2-letters': 'vl', 'first3-letters': 'vla', 'last-letter': 'r', 'last2-letters': 'ir', 'last3-letters': 'mir'}
 {'first-letter': 'm', 'first2-letters': 'mo', 'first3-letters': 'moh', 'last-letter': 'd', 'last2-letters': 'ed', 'last3-letters': 'med'}]


In [47]:
# Extract the features for the dataset
df_X = features(df_names['name'])

In [48]:
df_y = df_names['sex']

In [50]:
from sklearn.feature_extraction import DictVectorizer
 
corpus = features(["Mike", "Julia"])
dv = DictVectorizer() #new vectorizer in addition to count vectorizer, tf-idf
dv.fit(corpus)
transformed = dv.transform(corpus)
print(transformed)

  (0, 1)	1.0
  (0, 3)	1.0
  (0, 5)	1.0
  (0, 7)	1.0
  (0, 9)	1.0
  (0, 10)	1.0
  (1, 0)	1.0
  (1, 2)	1.0
  (1, 4)	1.0
  (1, 6)	1.0
  (1, 8)	1.0
  (1, 11)	1.0


In [51]:
dv.get_feature_names()

['first-letter=j',
 'first-letter=m',
 'first2-letters=ju',
 'first2-letters=mi',
 'first3-letters=jul',
 'first3-letters=mik',
 'last-letter=a',
 'last-letter=e',
 'last2-letters=ia',
 'last2-letters=ke',
 'last3-letters=ike',
 'last3-letters=lia']

In [52]:
# Train Test Split
dfX_train, dfX_test, dfy_train, dfy_test = train_test_split(df_X, df_y, test_size=0.33, random_state=42)

In [53]:
dfX_train #check, it uses features function

array([{'first-letter': 'e', 'first2-letters': 'el', 'first3-letters': 'ele', 'last-letter': 'a', 'last2-letters': 'ia', 'last3-letters': 'nia'},
       {'first-letter': 'a', 'first2-letters': 'ad', 'first3-letters': 'adi', 'last-letter': 'l', 'last2-letters': 'il', 'last3-letters': 'dil'},
       {'first-letter': 'k', 'first2-letters': 'ka', 'first3-letters': 'kad', 'last-letter': 'e', 'last2-letters': 'ze', 'last3-letters': 'nze'},
       ...,
       {'first-letter': 'j', 'first2-letters': 'ja', 'first3-letters': 'jaz', 'last-letter': 'y', 'last2-letters': 'ly', 'last3-letters': 'zly'},
       {'first-letter': 'e', 'first2-letters': 'el', 'first3-letters': 'elv', 'last-letter': 'a', 'last2-letters': 'na', 'last3-letters': 'ina'},
       {'first-letter': 'l', 'first2-letters': 'le', 'first3-letters': 'led', 'last-letter': 'r', 'last2-letters': 'er', 'last3-letters': 'ger'}],
      dtype=object)

In [54]:
dv = DictVectorizer()
dv.fit_transform(dfX_train)

<63666x8194 sparse matrix of type '<class 'numpy.float64'>'
	with 381996 stored elements in Compressed Sparse Row format>

In [55]:
# Model building Using DecisionTree

from sklearn.tree import DecisionTreeClassifier
 
dclf = DecisionTreeClassifier()
my_xfeatures =dv.transform(dfX_train)
dclf.fit(my_xfeatures, dfy_train)

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=None,
            splitter='best')

In [58]:

name_eg1 = ["venkatesan"]
transform_dv =dv.transform(features(name_eg1))
vect4 = transform_dv.toarray()
if dclf.predict(vect4) == 0:
    print("Female")
else:
    print("Male")

Male


In [59]:

name_eg1 = ["Balaji"]
transform_dv =dv.transform(features(name_eg1))
vect4 = transform_dv.toarray()
if dclf.predict(vect4) == 0:
    print("Female")
else:
    print("Male")

Male


In [60]:

name_eg1 = ["Deepa"]
transform_dv =dv.transform(features(name_eg1))
vect4 = transform_dv.toarray()
if dclf.predict(vect4) == 0:
    print("Female")
else:
    print("Male")

Female


In [61]:
# Second Prediction With Nigerian Name
name_eg1 = ["Prakash"]
transform_dv =dv.transform(features(name_eg1))
vect4 = transform_dv.toarray()
if dclf.predict(vect4) == 0:
    print("Female")
else:
    print("Male")

Male


In [62]:
name_eg1 = ["lakshmi"]
transform_dv =dv.transform(features(name_eg1))
vect4 = transform_dv.toarray()
if dclf.predict(vect4) == 0:
    print("Female")
else:
    print("Male")

Female


In [63]:
# A function to do it
def genderpredictor1(a):
    test_name1 = [a]
    transform_dv =dv.transform(features(test_name1))
    vector = transform_dv.toarray()
    if dclf.predict(vector) == 0:
        print("Female")
    else:
        print("Male")

In [67]:
genderpredictor1("Abdul kalam")

Male


# Model Saving

# Also we can download the model from the home by tik the file and download button with the pkl format itself

In [68]:
from sklearn.externals import joblib

In [69]:
decisiontreModel = open("decisiontreemodel.pkl","wb")

In [70]:
joblib.dump(dclf,decisiontreModel) # clf refers to classifier

In [71]:
decisiontreModel.close

<function BufferedWriter.close>

# Alternative to Model Saving

In [72]:

import pickle
dctreeModel = open("namesdetectormodel.pkl","wb")

In [73]:
pickle.dump(dclf,dctreeModel) # clf refers to classifier

In [74]:
dctreeModel.close()

# Saving naive bayes

In [75]:
NaiveBayesModel = open("naivebayesgendermodel.pkl","wb")

In [76]:
joblib.dump(clf,NaiveBayesModel)

In [77]:
NaiveBayesModel.close()