# I think it (Word2vec(Custom Dataset)) should be done in google collab because training takes much time

In [1]:
from tensorflow.keras.preprocessing.text import one_hot

In [2]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [3]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [4]:
### Vocabulary size
voc_size=10000

In [5]:
onehot_repr=[one_hot(words,voc_size)for words in sent] 
print(onehot_repr)

[[8156, 7733, 5843, 8318], [8156, 7733, 5843, 2684], [8156, 2995, 5843, 7674], [9623, 2192, 7347, 1949, 6581], [9623, 2192, 7347, 1949, 6476], [8482, 8156, 2209, 5843, 2508], [3187, 7930, 9028, 1949]]


In [6]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential

In [7]:
import numpy as np

In [8]:
sent_length=8
embedded_docs=pad_sequences(onehot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 8156 7733 5843 8318]
 [   0    0    0    0 8156 7733 5843 2684]
 [   0    0    0    0 8156 2995 5843 7674]
 [   0    0    0 9623 2192 7347 1949 6581]
 [   0    0    0 9623 2192 7347 1949 6476]
 [   0    0    0 8482 8156 2209 5843 2508]
 [   0    0    0    0 3187 7930 9028 1949]]


In [18]:
dim=10 # feature dimension

In [10]:
model=Sequential()
model.add(Embedding(voc_size,10,input_length=sent_length))
model.compile('adam','mse')

In [11]:
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding (Embedding)        (None, 8, 10)             100000    
Total params: 100,000
Trainable params: 100,000
Non-trainable params: 0
_________________________________________________________________


In [12]:
print(model.predict(embedded_docs))

[[[ 0.04769896  0.00485985  0.01890281 -0.00371278  0.0050483
   -0.00462384  0.01622324  0.02411025 -0.04226141 -0.03230971]
  [ 0.04769896  0.00485985  0.01890281 -0.00371278  0.0050483
   -0.00462384  0.01622324  0.02411025 -0.04226141 -0.03230971]
  [ 0.04769896  0.00485985  0.01890281 -0.00371278  0.0050483
   -0.00462384  0.01622324  0.02411025 -0.04226141 -0.03230971]
  [ 0.04769896  0.00485985  0.01890281 -0.00371278  0.0050483
   -0.00462384  0.01622324  0.02411025 -0.04226141 -0.03230971]
  [ 0.01425058  0.04248704 -0.00134582  0.02569545  0.01073151
    0.02557537  0.01148614 -0.00898279  0.04066087  0.00968064]
  [ 0.03075056 -0.00884225 -0.03100656 -0.01818077  0.00403762
    0.00545281 -0.00840428 -0.01647262 -0.01128569 -0.04548464]
  [-0.00235061  0.03501542 -0.01393796 -0.01894292 -0.02616055
    0.0108968   0.01887024 -0.04916943  0.04451165  0.01698821]
  [ 0.03090937  0.03935594  0.03496719 -0.04970418 -0.01968281
    0.02387165 -0.0060745  -0.02082138  0.03752235  

In [21]:
embedded_docs[0]

array([   0,    0,    0,    0, 8156, 7733, 5843, 8318])

In [27]:
print(model.predict(embedded_docs)[0][0]) # gives the probability values

[ 0.04769896  0.00485985  0.01890281 -0.00371278  0.0050483  -0.00462384
  0.01622324  0.02411025 -0.04226141 -0.03230971]


In [28]:
print(len(model.predict(embedded_docs)[0][0])) # dimension value

10


In [24]:
model.predict(embedded_docs)

array([[[ 0.04769896,  0.00485985,  0.01890281, -0.00371278,
          0.0050483 , -0.00462384,  0.01622324,  0.02411025,
         -0.04226141, -0.03230971],
        [ 0.04769896,  0.00485985,  0.01890281, -0.00371278,
          0.0050483 , -0.00462384,  0.01622324,  0.02411025,
         -0.04226141, -0.03230971],
        [ 0.04769896,  0.00485985,  0.01890281, -0.00371278,
          0.0050483 , -0.00462384,  0.01622324,  0.02411025,
         -0.04226141, -0.03230971],
        [ 0.04769896,  0.00485985,  0.01890281, -0.00371278,
          0.0050483 , -0.00462384,  0.01622324,  0.02411025,
         -0.04226141, -0.03230971],
        [ 0.01425058,  0.04248704, -0.00134582,  0.02569545,
          0.01073151,  0.02557537,  0.01148614, -0.00898279,
          0.04066087,  0.00968064],
        [ 0.03075056, -0.00884225, -0.03100656, -0.01818077,
          0.00403762,  0.00545281, -0.00840428, -0.01647262,
         -0.01128569, -0.04548464],
        [-0.00235061,  0.03501542, -0.01393796, -0.0