In [14]:
import mxnet as mx
import numpy as np
import logging


logging.basicConfig(level=logging.INFO)
sample_count = 1000
train_count = 800
valid_count = sample_count - train_count
feature_count = 100
category_count = 10
batch=10

In [15]:
a = mx.nd.array([[1,2,3], [4,5,6]])

In [16]:
a.size

6

In [17]:
a.shape

(2, 3)

In [18]:
X = mx.nd.uniform(low=0, high=1, shape=(sample_count, feature_count))
X


[[0.36371076 0.32504722 0.57019675 ... 0.16494046 0.13002858 0.5247994 ]
 [0.01936696 0.08362301 0.6788355  ... 0.79820037 0.54420817 0.8141384 ]
 [0.08209492 0.94809043 0.3663424  ... 0.7605785  0.20137872 0.0637698 ]
 ...
 [0.19279832 0.55113155 0.79755664 ... 0.8880615  0.82723254 0.32272264]
 [0.16283217 0.36928758 0.42668995 ... 0.5330033  0.3544119  0.5887649 ]
 [0.00233414 0.11826316 0.72051543 ... 0.9533956  0.08521933 0.5664016 ]]
<NDArray 1000x100 @cpu(0)>

In [19]:
Y = mx.nd.empty((sample_count,))
for i in range(0,sample_count-1):
  Y[i] = np.random.randint(0,category_count)

In [20]:
#split the data
X_train = mx.nd.crop(X, begin=(0,0), end=(train_count,feature_count-1))
X_valid = mx.nd.crop(X, begin=(train_count,0), end=(sample_count,feature_count-1))
Y_train = Y[0:train_count]
Y_valid = Y[train_count:sample_count]

In [21]:
data = mx.sym.Variable('data')
fc1 = mx.sym.FullyConnected(data, name='fc1', num_hidden=64)
relu1 = mx.sym.Activation(fc1, name='relu1', act_type="relu")
fc2 = mx.sym.FullyConnected(relu1, name='fc2', num_hidden=category_count)
out = mx.sym.SoftmaxOutput(fc2, name='softmax')
mod = mx.mod.Module(out)

In [24]:
train_iter = mx.io.NDArrayIter(data=X_train,label=Y_train,batch_size=batch)
mod.bind(data_shapes=[('data', (128,20))], label_shapes=[('softmax_label', (128,))])

In [25]:
mod.init_params()
#Much better
mod.init_params(initializer=mx.init.Xavier(magnitude=2.))
mod.init_optimizer(optimizer='sgd', optimizer_params=(('learning_rate', 0.1), ))

G:\New folder\envs\pytorch\lib\site-packages\ipykernel_launcher.py:3: UserWarning: Parameters already initialized and force_init=False. init_params call ignored.
  This is separate from the ipykernel package so we can avoid doing imports until


In [33]:
a=set(["h","e","l","l","o"])
a

{'e', 'h', 'l', 'o'}

In [34]:
import torch
a = torch.range(1, 16)

G:\New folder\envs\pytorch\lib\site-packages\ipykernel_launcher.py:2: UserWarning: torch.range is deprecated in favor of torch.arange and will be removed in 0.5. Note that arange generates values in [start; end), not [start; end].
  


In [41]:
type(a)

torch.Tensor

In [38]:
b=a.view(16,-1)

In [40]:
type(b)

torch.Tensor

In [50]:
b

tensor([[ 1.],
        [ 2.],
        [ 3.],
        [ 4.],
        [ 5.],
        [ 6.],
        [ 7.],
        [ 8.],
        [ 9.],
        [10.],
        [11.],
        [12.],
        [13.],
        [14.],
        [15.],
        [16.]])

In [48]:
a = a.view(-1,16)

In [49]:
a

tensor([[ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13., 14.,
         15., 16.]])