In [222]:
import librosa
from librosa import display

import matplotlib.pyplot as plt
%matplotlib inline
import os
import pandas as pd
import glob 
import numpy as np

In [223]:
import time
#path='C:\\Users\\2304373\\Downloads\\Emotion-Detection-in-Speech-master\\Emotion-Detection-in-Speech-master\\Emotion Detection in Speech\\data\\RAVDESS\\'
#path = 'C:\\Users\\2304373\\Downloads\\to do python files\\speech-emotion-recognition-master\\speech-emotion-recognition-master\\dataset\\'

#path='C:\\Users\\2304373\\Downloads\\Emotion-Detection-in-Speech-master\\Emotion-Detection-in-Speech-master\\Emotion Detection in Speech\\data\\SAVEE'
lst = []

df=pd.DataFrame()

start_time = time.time()

for i in range(1,6):
    for file in glob.glob("C:\\Users\\2304373\\Downloads\\Emotion-Detection-in-Speech-master\\Emotion-Detection-in-Speech-master\\Emotion Detection in Speech\\RAVDESS\\*\\*.wav".format(i)):
        #Load librosa array, obtain mfcss, store the file and the mcss information in a new array
        X, sample_rate = librosa.load(os.path.join(file), res_type='kaiser_fast')
        mfccs = np.mean(librosa.feature.mfcc(y=X, sr=sample_rate, n_mfcc=40).T,axis=0) 
        # The instruction below converts the labels (from 1 to 8) to a series from 0 to 7
        # This is because our predictor needs to start from 0 otherwise it will try to predict also 0.
        #file = int(file[7:8]) - 1 
        file=os.path.basename(file)
        arr = mfccs, file
        lst.append(arr)
        #df=df.append(arr)
      # If the file is not valid, skip it
      

print("--- Data loaded. Loading time: %s seconds ---" % (time.time() - start_time))

--- Data loaded. Loading time: 620.2212450504303 seconds ---


In [224]:
file

'03-01-04-02-02-02-24.wav'

In [276]:
lst[5844]

(array([-6.68426602e+02,  4.50779139e+01, -4.49340704e+00,  3.37134248e+00,
        -1.25355343e+01, -2.39312228e+00, -1.25292559e+01, -6.53176967e+00,
        -1.52432347e+01, -8.18102950e-01, -1.17225678e+01, -1.40473053e+00,
        -5.32158657e+00, -4.30280566e+00, -2.77964838e+00, -5.08235132e+00,
        -4.16559132e+00, -2.86873109e-01, -4.53241575e+00, -8.23480494e-01,
        -3.17831754e+00, -1.21789561e+00, -1.99177815e+00,  6.55079700e-01,
         2.43235761e-01,  5.68695485e+00,  5.02663363e+00,  9.41428108e+00,
         5.89406500e+00,  3.76940920e+00,  1.36149654e+00, -1.44035805e+00,
        -3.80817380e-01, -5.44273798e-01,  4.04518345e-01, -1.57976340e+00,
        -2.39487245e+00, -1.68125690e+00, -2.16080182e+00, -1.47322194e+00]),
 '03-01-04-02-02-02-24.wav')

In [270]:
X, y = zip(*lst)


In [274]:
print(X[5844])

[-6.68426602e+02  4.50779139e+01 -4.49340704e+00  3.37134248e+00
 -1.25355343e+01 -2.39312228e+00 -1.25292559e+01 -6.53176967e+00
 -1.52432347e+01 -8.18102950e-01 -1.17225678e+01 -1.40473053e+00
 -5.32158657e+00 -4.30280566e+00 -2.77964838e+00 -5.08235132e+00
 -4.16559132e+00 -2.86873109e-01 -4.53241575e+00 -8.23480494e-01
 -3.17831754e+00 -1.21789561e+00 -1.99177815e+00  6.55079700e-01
  2.43235761e-01  5.68695485e+00  5.02663363e+00  9.41428108e+00
  5.89406500e+00  3.76940920e+00  1.36149654e+00 -1.44035805e+00
 -3.80817380e-01 -5.44273798e-01  4.04518345e-01 -1.57976340e+00
 -2.39487245e+00 -1.68125690e+00 -2.16080182e+00 -1.47322194e+00]


In [288]:
type(X)

list

In [229]:
len(y)


5845

In [230]:
len(set(y))

1169

In [231]:
for i in y:
    print(i, end="\n ")

03-01-05-01-01-01-01.wav
 03-01-05-01-01-01-02.wav
 03-01-05-01-01-01-05.wav
 03-01-05-01-01-01-06.wav
 03-01-05-01-01-01-07.wav
 03-01-05-01-01-01-09.wav
 03-01-05-01-01-01-11.wav
 03-01-05-01-01-01-12.wav
 03-01-05-01-01-01-13.wav
 03-01-05-01-01-01-14.wav
 03-01-05-01-01-01-19.wav
 03-01-05-01-01-01-20.wav
 03-01-05-01-01-01-23.wav
 03-01-05-01-01-01-24.wav
 03-01-05-01-01-02-01.wav
 03-01-05-01-01-02-02.wav
 03-01-05-01-01-02-03.wav
 03-01-05-01-01-02-05.wav
 03-01-05-01-01-02-06.wav
 03-01-05-01-01-02-07.wav
 03-01-05-01-01-02-11.wav
 03-01-05-01-01-02-12.wav
 03-01-05-01-01-02-13.wav
 03-01-05-01-01-02-14.wav
 03-01-05-01-01-02-15.wav
 03-01-05-01-01-02-20.wav
 03-01-05-01-01-02-23.wav
 03-01-05-01-01-02-24.wav
 03-01-05-01-02-01-01.wav
 03-01-05-01-02-01-02.wav
 03-01-05-01-02-01-05.wav
 03-01-05-01-02-01-06.wav
 03-01-05-01-02-01-07.wav
 03-01-05-01-02-01-09.wav
 03-01-05-01-02-01-11.wav
 03-01-05-01-02-01-12.wav
 03-01-05-01-02-01-13.wav
 03-01-05-01-02-01-14.wav
 03-01-05-01-

 03-01-02-02-02-01-13.wav
 03-01-02-02-02-01-14.wav
 03-01-02-02-02-01-15.wav
 03-01-02-02-02-01-16.wav
 03-01-02-02-02-01-17.wav
 03-01-02-02-02-01-18.wav
 03-01-02-02-02-01-19.wav
 03-01-02-02-02-01-20.wav
 03-01-02-02-02-01-21.wav
 03-01-02-02-02-01-22.wav
 03-01-02-02-02-01-23.wav
 03-01-02-02-02-01-24.wav
 03-01-02-02-02-02-01.wav
 03-01-02-02-02-02-02.wav
 03-01-02-02-02-02-03.wav
 03-01-02-02-02-02-04.wav
 03-01-02-02-02-02-05.wav
 03-01-02-02-02-02-06.wav
 03-01-02-02-02-02-07.wav
 03-01-02-02-02-02-08.wav
 03-01-02-02-02-02-09.wav
 03-01-02-02-02-02-10.wav
 03-01-02-02-02-02-11.wav
 03-01-02-02-02-02-12.wav
 03-01-02-02-02-02-13.wav
 03-01-02-02-02-02-14.wav
 03-01-02-02-02-02-15.wav
 03-01-02-02-02-02-16.wav
 03-01-02-02-02-02-17.wav
 03-01-02-02-02-02-18.wav
 03-01-02-02-02-02-19.wav
 03-01-02-02-02-02-20.wav
 03-01-02-02-02-02-21.wav
 03-01-02-02-02-02-22.wav
 03-01-02-02-02-02-23.wav
 03-01-02-02-02-02-24.wav
 03-01-07-01-01-01-01.wav
 03-01-07-01-01-01-02.wav
 03-01-07-01

 03-01-06-02-02-02-04.wav
 03-01-06-02-02-02-05.wav
 03-01-06-02-02-02-06.wav
 03-01-06-02-02-02-07.wav
 03-01-06-02-02-02-08.wav
 03-01-06-02-02-02-09.wav
 03-01-06-02-02-02-10.wav
 03-01-06-02-02-02-11.wav
 03-01-06-02-02-02-12.wav
 03-01-06-02-02-02-13.wav
 03-01-06-02-02-02-14.wav
 03-01-06-02-02-02-15.wav
 03-01-06-02-02-02-16.wav
 03-01-06-02-02-02-17.wav
 03-01-06-02-02-02-18.wav
 03-01-06-02-02-02-19.wav
 03-01-06-02-02-02-20.wav
 03-01-06-02-02-02-21.wav
 03-01-06-02-02-02-22.wav
 03-01-06-02-02-02-23.wav
 03-01-06-02-02-02-24.wav
 03-01-03-01-01-01-01.wav
 03-01-03-01-01-01-02.wav
 03-01-03-01-01-01-03.wav
 03-01-03-01-01-01-04.wav
 03-01-03-01-01-01-05.wav
 03-01-03-01-01-01-06.wav
 03-01-03-01-01-01-07.wav
 03-01-03-01-01-01-08.wav
 03-01-03-01-01-01-09.wav
 03-01-03-01-01-01-10.wav
 03-01-03-01-01-01-11.wav
 03-01-03-01-01-01-12.wav
 03-01-03-01-01-01-13.wav
 03-01-03-01-01-01-14.wav
 03-01-03-01-01-01-15.wav
 03-01-03-01-01-01-16.wav
 03-01-03-01-01-01-17.wav
 03-01-03-01

 03-01-01-01-02-01-02.wav
 03-01-01-01-02-01-03.wav
 03-01-01-01-02-01-04.wav
 03-01-01-01-02-01-05.wav
 03-01-01-01-02-01-06.wav
 03-01-01-01-02-01-07.wav
 03-01-01-01-02-01-08.wav
 03-01-01-01-02-01-09.wav
 03-01-01-01-02-01-10.wav
 03-01-01-01-02-01-11.wav
 03-01-01-01-02-01-12.wav
 03-01-01-01-02-01-13.wav
 03-01-01-01-02-01-14.wav
 03-01-01-01-02-01-15.wav
 03-01-01-01-02-01-16.wav
 03-01-01-01-02-01-17.wav
 03-01-01-01-02-01-18.wav
 03-01-01-01-02-01-19.wav
 03-01-01-01-02-01-20.wav
 03-01-01-01-02-01-21.wav
 03-01-01-01-02-01-22.wav
 03-01-01-01-02-01-23.wav
 03-01-01-01-02-01-24.wav
 03-01-01-01-02-02-01.wav
 03-01-01-01-02-02-02.wav
 03-01-01-01-02-02-03.wav
 03-01-01-01-02-02-04.wav
 03-01-01-01-02-02-05.wav
 03-01-01-01-02-02-06.wav
 03-01-01-01-02-02-07.wav
 03-01-01-01-02-02-08.wav
 03-01-01-01-02-02-09.wav
 03-01-01-01-02-02-10.wav
 03-01-01-01-02-02-11.wav
 03-01-01-01-02-02-12.wav
 03-01-01-01-02-02-13.wav
 03-01-01-01-02-02-14.wav
 03-01-01-01-02-02-15.wav
 03-01-01-01

 03-01-01-01-01-02-03.wav
 03-01-01-01-01-02-04.wav
 03-01-01-01-01-02-05.wav
 03-01-01-01-01-02-06.wav
 03-01-01-01-01-02-07.wav
 03-01-01-01-01-02-08.wav
 03-01-01-01-01-02-09.wav
 03-01-01-01-01-02-10.wav
 03-01-01-01-01-02-11.wav
 03-01-01-01-01-02-12.wav
 03-01-01-01-01-02-13.wav
 03-01-01-01-01-02-14.wav
 03-01-01-01-01-02-15.wav
 03-01-01-01-01-02-16.wav
 03-01-01-01-01-02-17.wav
 03-01-01-01-01-02-18.wav
 03-01-01-01-01-02-19.wav
 03-01-01-01-01-02-20.wav
 03-01-01-01-01-02-21.wav
 03-01-01-01-01-02-22.wav
 03-01-01-01-01-02-23.wav
 03-01-01-01-01-02-24.wav
 03-01-01-01-02-01-01.wav
 03-01-01-01-02-01-02.wav
 03-01-01-01-02-01-03.wav
 03-01-01-01-02-01-04.wav
 03-01-01-01-02-01-05.wav
 03-01-01-01-02-01-06.wav
 03-01-01-01-02-01-07.wav
 03-01-01-01-02-01-08.wav
 03-01-01-01-02-01-09.wav
 03-01-01-01-02-01-10.wav
 03-01-01-01-02-01-11.wav
 03-01-01-01-02-01-12.wav
 03-01-01-01-02-01-13.wav
 03-01-01-01-02-01-14.wav
 03-01-01-01-02-01-15.wav
 03-01-01-01-02-01-16.wav
 03-01-01-01

In [283]:
p=y[0:113]
len(set(p))

113

In [233]:
p

('03-01-05-01-01-01-01.wav',
 '03-01-05-01-01-01-02.wav',
 '03-01-05-01-01-01-05.wav',
 '03-01-05-01-01-01-06.wav',
 '03-01-05-01-01-01-07.wav',
 '03-01-05-01-01-01-09.wav',
 '03-01-05-01-01-01-11.wav',
 '03-01-05-01-01-01-12.wav',
 '03-01-05-01-01-01-13.wav',
 '03-01-05-01-01-01-14.wav',
 '03-01-05-01-01-01-19.wav',
 '03-01-05-01-01-01-20.wav',
 '03-01-05-01-01-01-23.wav',
 '03-01-05-01-01-01-24.wav',
 '03-01-05-01-01-02-01.wav',
 '03-01-05-01-01-02-02.wav',
 '03-01-05-01-01-02-03.wav',
 '03-01-05-01-01-02-05.wav',
 '03-01-05-01-01-02-06.wav',
 '03-01-05-01-01-02-07.wav',
 '03-01-05-01-01-02-11.wav',
 '03-01-05-01-01-02-12.wav',
 '03-01-05-01-01-02-13.wav',
 '03-01-05-01-01-02-14.wav',
 '03-01-05-01-01-02-15.wav',
 '03-01-05-01-01-02-20.wav',
 '03-01-05-01-01-02-23.wav',
 '03-01-05-01-01-02-24.wav',
 '03-01-05-01-02-01-01.wav',
 '03-01-05-01-02-01-02.wav',
 '03-01-05-01-02-01-05.wav',
 '03-01-05-01-02-01-06.wav',
 '03-01-05-01-02-01-07.wav',
 '03-01-05-01-02-01-09.wav',
 '03-01-05-01-

In [285]:
c = dict(zip(p,[0 for x in range(0,len(p))]))
len(c)
c

{'03-01-05-01-01-01-01.wav': 0,
 '03-01-05-01-01-01-02.wav': 0,
 '03-01-05-01-01-01-05.wav': 0,
 '03-01-05-01-01-01-06.wav': 0,
 '03-01-05-01-01-01-07.wav': 0,
 '03-01-05-01-01-01-09.wav': 0,
 '03-01-05-01-01-01-11.wav': 0,
 '03-01-05-01-01-01-12.wav': 0,
 '03-01-05-01-01-01-13.wav': 0,
 '03-01-05-01-01-01-14.wav': 0,
 '03-01-05-01-01-01-19.wav': 0,
 '03-01-05-01-01-01-20.wav': 0,
 '03-01-05-01-01-01-23.wav': 0,
 '03-01-05-01-01-01-24.wav': 0,
 '03-01-05-01-01-02-01.wav': 0,
 '03-01-05-01-01-02-02.wav': 0,
 '03-01-05-01-01-02-03.wav': 0,
 '03-01-05-01-01-02-05.wav': 0,
 '03-01-05-01-01-02-06.wav': 0,
 '03-01-05-01-01-02-07.wav': 0,
 '03-01-05-01-01-02-11.wav': 0,
 '03-01-05-01-01-02-12.wav': 0,
 '03-01-05-01-01-02-13.wav': 0,
 '03-01-05-01-01-02-14.wav': 0,
 '03-01-05-01-01-02-15.wav': 0,
 '03-01-05-01-01-02-20.wav': 0,
 '03-01-05-01-01-02-23.wav': 0,
 '03-01-05-01-01-02-24.wav': 0,
 '03-01-05-01-02-01-01.wav': 0,
 '03-01-05-01-02-01-02.wav': 0,
 '03-01-05-01-02-01-05.wav': 0,
 '03-01-

In [280]:
l1=list(c.values())
len(l1)

113

In [236]:
for i in l1:
    print(i, end=" ")

0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 

In [237]:
q=y[113:305]
len(set(q))

192

In [238]:
q

('03-01-02-01-01-01-01.wav',
 '03-01-02-01-01-01-02.wav',
 '03-01-02-01-01-01-03.wav',
 '03-01-02-01-01-01-04.wav',
 '03-01-02-01-01-01-05.wav',
 '03-01-02-01-01-01-06.wav',
 '03-01-02-01-01-01-07.wav',
 '03-01-02-01-01-01-08.wav',
 '03-01-02-01-01-01-09.wav',
 '03-01-02-01-01-01-10.wav',
 '03-01-02-01-01-01-11.wav',
 '03-01-02-01-01-01-12.wav',
 '03-01-02-01-01-01-13.wav',
 '03-01-02-01-01-01-14.wav',
 '03-01-02-01-01-01-15.wav',
 '03-01-02-01-01-01-16.wav',
 '03-01-02-01-01-01-17.wav',
 '03-01-02-01-01-01-18.wav',
 '03-01-02-01-01-01-19.wav',
 '03-01-02-01-01-01-20.wav',
 '03-01-02-01-01-01-21.wav',
 '03-01-02-01-01-01-22.wav',
 '03-01-02-01-01-01-23.wav',
 '03-01-02-01-01-01-24.wav',
 '03-01-02-01-01-02-01.wav',
 '03-01-02-01-01-02-02.wav',
 '03-01-02-01-01-02-03.wav',
 '03-01-02-01-01-02-04.wav',
 '03-01-02-01-01-02-05.wav',
 '03-01-02-01-01-02-06.wav',
 '03-01-02-01-01-02-07.wav',
 '03-01-02-01-01-02-08.wav',
 '03-01-02-01-01-02-09.wav',
 '03-01-02-01-01-02-10.wav',
 '03-01-02-01-

In [239]:
d = dict(zip(q,[1 for x in range(0,len(q))]))
d
len(d)

192

In [240]:
l2=list(d.values())
len(l2)

192

In [241]:
d

{'03-01-02-01-01-01-01.wav': 1,
 '03-01-02-01-01-01-02.wav': 1,
 '03-01-02-01-01-01-03.wav': 1,
 '03-01-02-01-01-01-04.wav': 1,
 '03-01-02-01-01-01-05.wav': 1,
 '03-01-02-01-01-01-06.wav': 1,
 '03-01-02-01-01-01-07.wav': 1,
 '03-01-02-01-01-01-08.wav': 1,
 '03-01-02-01-01-01-09.wav': 1,
 '03-01-02-01-01-01-10.wav': 1,
 '03-01-02-01-01-01-11.wav': 1,
 '03-01-02-01-01-01-12.wav': 1,
 '03-01-02-01-01-01-13.wav': 1,
 '03-01-02-01-01-01-14.wav': 1,
 '03-01-02-01-01-01-15.wav': 1,
 '03-01-02-01-01-01-16.wav': 1,
 '03-01-02-01-01-01-17.wav': 1,
 '03-01-02-01-01-01-18.wav': 1,
 '03-01-02-01-01-01-19.wav': 1,
 '03-01-02-01-01-01-20.wav': 1,
 '03-01-02-01-01-01-21.wav': 1,
 '03-01-02-01-01-01-22.wav': 1,
 '03-01-02-01-01-01-23.wav': 1,
 '03-01-02-01-01-01-24.wav': 1,
 '03-01-02-01-01-02-01.wav': 1,
 '03-01-02-01-01-02-02.wav': 1,
 '03-01-02-01-01-02-03.wav': 1,
 '03-01-02-01-01-02-04.wav': 1,
 '03-01-02-01-01-02-05.wav': 1,
 '03-01-02-01-01-02-06.wav': 1,
 '03-01-02-01-01-02-07.wav': 1,
 '03-01-

In [242]:
len(d)

192

In [243]:
d['03-01-02-01-01-02-14.wav']

1

In [244]:
l2=list(d.values())
for i in l2:
    print(i, end=" ")

1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 

In [245]:
r=y[305:497]

In [246]:
e = dict(zip(r,[2 for x in range(0,len(r))]))
len(e)

192

In [247]:
e

{'03-01-07-01-01-01-01.wav': 2,
 '03-01-07-01-01-01-02.wav': 2,
 '03-01-07-01-01-01-03.wav': 2,
 '03-01-07-01-01-01-04.wav': 2,
 '03-01-07-01-01-01-05.wav': 2,
 '03-01-07-01-01-01-06.wav': 2,
 '03-01-07-01-01-01-07.wav': 2,
 '03-01-07-01-01-01-08.wav': 2,
 '03-01-07-01-01-01-09.wav': 2,
 '03-01-07-01-01-01-10.wav': 2,
 '03-01-07-01-01-01-11.wav': 2,
 '03-01-07-01-01-01-12.wav': 2,
 '03-01-07-01-01-01-13.wav': 2,
 '03-01-07-01-01-01-14.wav': 2,
 '03-01-07-01-01-01-15.wav': 2,
 '03-01-07-01-01-01-16.wav': 2,
 '03-01-07-01-01-01-17.wav': 2,
 '03-01-07-01-01-01-18.wav': 2,
 '03-01-07-01-01-01-19.wav': 2,
 '03-01-07-01-01-01-20.wav': 2,
 '03-01-07-01-01-01-21.wav': 2,
 '03-01-07-01-01-01-22.wav': 2,
 '03-01-07-01-01-01-23.wav': 2,
 '03-01-07-01-01-01-24.wav': 2,
 '03-01-07-01-01-02-01.wav': 2,
 '03-01-07-01-01-02-02.wav': 2,
 '03-01-07-01-01-02-03.wav': 2,
 '03-01-07-01-01-02-04.wav': 2,
 '03-01-07-01-01-02-05.wav': 2,
 '03-01-07-01-01-02-06.wav': 2,
 '03-01-07-01-01-02-07.wav': 2,
 '03-01-

In [248]:
l3=list(e.values())


In [249]:
s=y[497:689]

In [250]:
f = dict(zip(s,[3 for x in range(0,len(s))]))
f


{'03-01-06-01-01-01-01.wav': 3,
 '03-01-06-01-01-01-02.wav': 3,
 '03-01-06-01-01-01-03.wav': 3,
 '03-01-06-01-01-01-04.wav': 3,
 '03-01-06-01-01-01-05.wav': 3,
 '03-01-06-01-01-01-06.wav': 3,
 '03-01-06-01-01-01-07.wav': 3,
 '03-01-06-01-01-01-08.wav': 3,
 '03-01-06-01-01-01-09.wav': 3,
 '03-01-06-01-01-01-10.wav': 3,
 '03-01-06-01-01-01-11.wav': 3,
 '03-01-06-01-01-01-12.wav': 3,
 '03-01-06-01-01-01-13.wav': 3,
 '03-01-06-01-01-01-14.wav': 3,
 '03-01-06-01-01-01-15.wav': 3,
 '03-01-06-01-01-01-16.wav': 3,
 '03-01-06-01-01-01-17.wav': 3,
 '03-01-06-01-01-01-18.wav': 3,
 '03-01-06-01-01-01-19.wav': 3,
 '03-01-06-01-01-01-20.wav': 3,
 '03-01-06-01-01-01-21.wav': 3,
 '03-01-06-01-01-01-22.wav': 3,
 '03-01-06-01-01-01-23.wav': 3,
 '03-01-06-01-01-01-24.wav': 3,
 '03-01-06-01-01-02-01.wav': 3,
 '03-01-06-01-01-02-02.wav': 3,
 '03-01-06-01-01-02-03.wav': 3,
 '03-01-06-01-01-02-04.wav': 3,
 '03-01-06-01-01-02-05.wav': 3,
 '03-01-06-01-01-02-06.wav': 3,
 '03-01-06-01-01-02-07.wav': 3,
 '03-01-

In [251]:
l4=list(f.values())

In [252]:
T=y[689:881]

In [253]:
g = dict(zip(T,[4 for x in range(0,len(T))]))
g

{'03-01-03-01-01-01-01.wav': 4,
 '03-01-03-01-01-01-02.wav': 4,
 '03-01-03-01-01-01-03.wav': 4,
 '03-01-03-01-01-01-04.wav': 4,
 '03-01-03-01-01-01-05.wav': 4,
 '03-01-03-01-01-01-06.wav': 4,
 '03-01-03-01-01-01-07.wav': 4,
 '03-01-03-01-01-01-08.wav': 4,
 '03-01-03-01-01-01-09.wav': 4,
 '03-01-03-01-01-01-10.wav': 4,
 '03-01-03-01-01-01-11.wav': 4,
 '03-01-03-01-01-01-12.wav': 4,
 '03-01-03-01-01-01-13.wav': 4,
 '03-01-03-01-01-01-14.wav': 4,
 '03-01-03-01-01-01-15.wav': 4,
 '03-01-03-01-01-01-16.wav': 4,
 '03-01-03-01-01-01-17.wav': 4,
 '03-01-03-01-01-01-18.wav': 4,
 '03-01-03-01-01-01-19.wav': 4,
 '03-01-03-01-01-01-20.wav': 4,
 '03-01-03-01-01-01-21.wav': 4,
 '03-01-03-01-01-01-22.wav': 4,
 '03-01-03-01-01-01-23.wav': 4,
 '03-01-03-01-01-01-24.wav': 4,
 '03-01-03-01-01-02-01.wav': 4,
 '03-01-03-01-01-02-02.wav': 4,
 '03-01-03-01-01-02-03.wav': 4,
 '03-01-03-01-01-02-04.wav': 4,
 '03-01-03-01-01-02-05.wav': 4,
 '03-01-03-01-01-02-06.wav': 4,
 '03-01-03-01-01-02-07.wav': 4,
 '03-01-

In [254]:
l5=list(g.values())
len(l5)

192

In [255]:
v=y[881:977]
i=dict(zip(v,[5 for x in range(0,len(v))]))
l6=list(i.values())
i

{'03-01-01-01-01-01-01.wav': 5,
 '03-01-01-01-01-01-02.wav': 5,
 '03-01-01-01-01-01-03.wav': 5,
 '03-01-01-01-01-01-04.wav': 5,
 '03-01-01-01-01-01-05.wav': 5,
 '03-01-01-01-01-01-06.wav': 5,
 '03-01-01-01-01-01-07.wav': 5,
 '03-01-01-01-01-01-08.wav': 5,
 '03-01-01-01-01-01-09.wav': 5,
 '03-01-01-01-01-01-10.wav': 5,
 '03-01-01-01-01-01-11.wav': 5,
 '03-01-01-01-01-01-12.wav': 5,
 '03-01-01-01-01-01-13.wav': 5,
 '03-01-01-01-01-01-14.wav': 5,
 '03-01-01-01-01-01-15.wav': 5,
 '03-01-01-01-01-01-16.wav': 5,
 '03-01-01-01-01-01-17.wav': 5,
 '03-01-01-01-01-01-18.wav': 5,
 '03-01-01-01-01-01-19.wav': 5,
 '03-01-01-01-01-01-20.wav': 5,
 '03-01-01-01-01-01-21.wav': 5,
 '03-01-01-01-01-01-22.wav': 5,
 '03-01-01-01-01-01-23.wav': 5,
 '03-01-01-01-01-01-24.wav': 5,
 '03-01-01-01-01-02-01.wav': 5,
 '03-01-01-01-01-02-02.wav': 5,
 '03-01-01-01-01-02-03.wav': 5,
 '03-01-01-01-01-02-04.wav': 5,
 '03-01-01-01-01-02-05.wav': 5,
 '03-01-01-01-01-02-06.wav': 5,
 '03-01-01-01-01-02-07.wav': 5,
 '03-01-

In [256]:
z=y[977:1169]
z

('03-01-04-01-01-01-01.wav',
 '03-01-04-01-01-01-02.wav',
 '03-01-04-01-01-01-03.wav',
 '03-01-04-01-01-01-04.wav',
 '03-01-04-01-01-01-05.wav',
 '03-01-04-01-01-01-06.wav',
 '03-01-04-01-01-01-07.wav',
 '03-01-04-01-01-01-08.wav',
 '03-01-04-01-01-01-09.wav',
 '03-01-04-01-01-01-10.wav',
 '03-01-04-01-01-01-11.wav',
 '03-01-04-01-01-01-12.wav',
 '03-01-04-01-01-01-13.wav',
 '03-01-04-01-01-01-14.wav',
 '03-01-04-01-01-01-15.wav',
 '03-01-04-01-01-01-16.wav',
 '03-01-04-01-01-01-17.wav',
 '03-01-04-01-01-01-18.wav',
 '03-01-04-01-01-01-19.wav',
 '03-01-04-01-01-01-20.wav',
 '03-01-04-01-01-01-21.wav',
 '03-01-04-01-01-01-22.wav',
 '03-01-04-01-01-01-23.wav',
 '03-01-04-01-01-01-24.wav',
 '03-01-04-01-01-02-01.wav',
 '03-01-04-01-01-02-02.wav',
 '03-01-04-01-01-02-03.wav',
 '03-01-04-01-01-02-04.wav',
 '03-01-04-01-01-02-05.wav',
 '03-01-04-01-01-02-06.wav',
 '03-01-04-01-01-02-07.wav',
 '03-01-04-01-01-02-08.wav',
 '03-01-04-01-01-02-09.wav',
 '03-01-04-01-01-02-10.wav',
 '03-01-04-01-

In [296]:
j=dict(zip(z,[6 for x in range(1,len(z))]))
j

{'03-01-04-01-01-01-01.wav': 6,
 '03-01-04-01-01-01-02.wav': 6,
 '03-01-04-01-01-01-03.wav': 6,
 '03-01-04-01-01-01-04.wav': 6,
 '03-01-04-01-01-01-05.wav': 6,
 '03-01-04-01-01-01-06.wav': 6,
 '03-01-04-01-01-01-07.wav': 6,
 '03-01-04-01-01-01-08.wav': 6,
 '03-01-04-01-01-01-09.wav': 6,
 '03-01-04-01-01-01-10.wav': 6,
 '03-01-04-01-01-01-11.wav': 6,
 '03-01-04-01-01-01-12.wav': 6,
 '03-01-04-01-01-01-13.wav': 6,
 '03-01-04-01-01-01-14.wav': 6,
 '03-01-04-01-01-01-15.wav': 6,
 '03-01-04-01-01-01-16.wav': 6,
 '03-01-04-01-01-01-17.wav': 6,
 '03-01-04-01-01-01-18.wav': 6,
 '03-01-04-01-01-01-19.wav': 6,
 '03-01-04-01-01-01-20.wav': 6,
 '03-01-04-01-01-01-21.wav': 6,
 '03-01-04-01-01-01-22.wav': 6,
 '03-01-04-01-01-01-23.wav': 6,
 '03-01-04-01-01-01-24.wav': 6,
 '03-01-04-01-01-02-01.wav': 6,
 '03-01-04-01-01-02-02.wav': 6,
 '03-01-04-01-01-02-03.wav': 6,
 '03-01-04-01-01-02-04.wav': 6,
 '03-01-04-01-01-02-05.wav': 6,
 '03-01-04-01-01-02-06.wav': 6,
 '03-01-04-01-01-02-07.wav': 6,
 '03-01-

In [299]:
l7=list(j.values())

In [178]:
k=y[1169:1360]

In [187]:
m=dict(zip(z,[7 for x in range(1,len(z))]))#here changed
m

{'03-01-04-01-01-01-01.wav': 7,
 '03-01-04-01-01-01-02.wav': 7,
 '03-01-04-01-01-01-03.wav': 7,
 '03-01-04-01-01-01-04.wav': 7,
 '03-01-04-01-01-01-05.wav': 7,
 '03-01-04-01-01-01-06.wav': 7,
 '03-01-04-01-01-01-07.wav': 7,
 '03-01-04-01-01-01-08.wav': 7,
 '03-01-04-01-01-01-09.wav': 7,
 '03-01-04-01-01-01-10.wav': 7,
 '03-01-04-01-01-01-11.wav': 7,
 '03-01-04-01-01-01-12.wav': 7,
 '03-01-04-01-01-01-13.wav': 7,
 '03-01-04-01-01-01-14.wav': 7,
 '03-01-04-01-01-01-15.wav': 7,
 '03-01-04-01-01-01-16.wav': 7,
 '03-01-04-01-01-01-17.wav': 7,
 '03-01-04-01-01-01-18.wav': 7,
 '03-01-04-01-01-01-19.wav': 7,
 '03-01-04-01-01-01-20.wav': 7,
 '03-01-04-01-01-01-21.wav': 7,
 '03-01-04-01-01-01-22.wav': 7,
 '03-01-04-01-01-01-23.wav': 7,
 '03-01-04-01-01-01-24.wav': 7,
 '03-01-04-01-01-02-01.wav': 7,
 '03-01-04-01-01-02-02.wav': 7,
 '03-01-04-01-01-02-03.wav': 7,
 '03-01-04-01-01-02-04.wav': 7,
 '03-01-04-01-01-02-05.wav': 7,
 '03-01-04-01-01-02-06.wav': 7,
 '03-01-04-01-01-02-07.wav': 7,
 '03-01-

In [183]:
l8=list(m.values())

In [307]:
total=l1+l2+l3+l4+l5+l6+l7
len(total)

1168

In [308]:
y=total

In [309]:
import numpy as np
arraylist = X
L = {array.tostring(): array for array in arraylist} # to remove the duplicate
L.values()

X=list(L.values())
len(X)

1168

In [310]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

In [311]:
from sklearn.tree import DecisionTreeClassifier

In [312]:
dtree = DecisionTreeClassifier()

In [313]:
dtree.fit(X_train, y_train)

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=None,
            splitter='best')

In [314]:
predictions = dtree.predict(X_test)

In [315]:
import numpy as np
x_traincnn = np.expand_dims(X_train, axis=2)
x_testcnn = np.expand_dims(X_test, axis=2)

In [316]:
x_traincnn.shape, x_testcnn.shape

((782, 40, 1), (386, 40, 1))

In [317]:
import keras
import numpy as np
import matplotlib.pyplot as plt
import tensorflow as tf
from keras.preprocessing import sequence
from keras.models import Sequential
from keras.layers import Dense, Embedding
from keras.utils import to_categorical
from keras.layers import Input, Flatten, Dropout, Activation
from keras.layers import Conv1D, MaxPooling1D
from keras.models import Model
from keras.callbacks import ModelCheckpoint

model = Sequential()

model.add(Conv1D(128, 5,padding='same',
                 input_shape=(40,1)))
model.add(Activation('relu'))
model.add(Dropout(0.1))
model.add(MaxPooling1D(pool_size=(8)))
model.add(Conv1D(128, 5,padding='same',))
model.add(Activation('relu'))
model.add(Dropout(0.1))
model.add(Flatten())
model.add(Dense(8))
model.add(Activation('softmax'))
opt = keras.optimizers.rmsprop(lr=0.00005, rho=0.9, epsilon=None, decay=0.0)

In [318]:
model.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv1d_5 (Conv1D)            (None, 40, 128)           768       
_________________________________________________________________
activation_7 (Activation)    (None, 40, 128)           0         
_________________________________________________________________
dropout_5 (Dropout)          (None, 40, 128)           0         
_________________________________________________________________
max_pooling1d_3 (MaxPooling1 (None, 5, 128)            0         
_________________________________________________________________
conv1d_6 (Conv1D)            (None, 5, 128)            82048     
_________________________________________________________________
activation_8 (Activation)    (None, 5, 128)            0         
_________________________________________________________________
dropout_6 (Dropout)          (None, 5, 128)            0         
__________

In [319]:
model.compile(loss='sparse_categorical_crossentropy',
              optimizer=opt,
              metrics=['accuracy'])

In [320]:
cnnhistory=model.fit(x_traincnn, y_train, batch_size=16, epochs=1000, validation_data=(x_testcnn, y_test))

Train on 782 samples, validate on 386 samples
Epoch 1/1000
782/782 [==============================] - 2s 3ms/step - loss: 8.3834 - acc: 0.1547 - val_loss: 3.6564 - val_acc: 0.1528
Epoch 2/1000
782/782 [==============================] - 1s 748us/step - loss: 6.9035 - acc: 0.1458 - val_loss: 2.3539 - val_acc: 0.1684
Epoch 3/1000
782/782 [==============================] - 1s 668us/step - loss: 6.6708 - acc: 0.1458 - val_loss: 2.9037 - val_acc: 0.1788
Epoch 4/1000
782/782 [==============================] - 1s 706us/step - loss: 6.1128 - acc: 0.1637 - val_loss: 2.1011 - val_acc: 0.2565
Epoch 5/1000
782/782 [==============================] - 1s 676us/step - loss: 5.7666 - acc: 0.1829 - val_loss: 2.1697 - val_acc: 0.2617
Epoch 6/1000
782/782 [==============================] - 1s 733us/step - loss: 5.3557 - acc: 0.1867 - val_loss: 2.2655 - val_acc: 0.2591
Epoch 7/1000
782/782 [==============================] - 1s 685us/step - loss: 5.5392 - acc: 0.1650 - val_loss: 1.9703 - val_acc: 0.2202
Epoc

782/782 [==============================] - 1s 684us/step - loss: 1.4530 - acc: 0.4284 - val_loss: 1.5339 - val_acc: 0.3860
Epoch 120/1000
782/782 [==============================] - 1s 723us/step - loss: 1.4399 - acc: 0.4514 - val_loss: 1.5216 - val_acc: 0.3964
Epoch 121/1000
782/782 [==============================] - 1s 727us/step - loss: 1.4510 - acc: 0.4322 - val_loss: 1.5404 - val_acc: 0.3912
Epoch 122/1000
782/782 [==============================] - 1s 697us/step - loss: 1.4252 - acc: 0.4476 - val_loss: 1.5291 - val_acc: 0.4067
Epoch 123/1000
782/782 [==============================] - 1s 702us/step - loss: 1.4313 - acc: 0.4527 - val_loss: 1.5370 - val_acc: 0.3964
Epoch 124/1000
782/782 [==============================] - 1s 738us/step - loss: 1.4042 - acc: 0.4910 - val_loss: 1.5181 - val_acc: 0.3860
Epoch 125/1000
782/782 [==============================] - 1s 698us/step - loss: 1.4302 - acc: 0.4629 - val_loss: 1.5135 - val_acc: 0.4016
Epoch 126/1000
782/782 [=========================

Epoch 237/1000
782/782 [==============================] - 1s 703us/step - loss: 1.1391 - acc: 0.5818 - val_loss: 1.3959 - val_acc: 0.4689
Epoch 238/1000
782/782 [==============================] - 1s 729us/step - loss: 1.1357 - acc: 0.5895 - val_loss: 1.3772 - val_acc: 0.4637
Epoch 239/1000
782/782 [==============================] - 1s 737us/step - loss: 1.1386 - acc: 0.5818 - val_loss: 1.3833 - val_acc: 0.4845
Epoch 240/1000
782/782 [==============================] - 1s 735us/step - loss: 1.1165 - acc: 0.6074 - val_loss: 1.4074 - val_acc: 0.4223
Epoch 241/1000
782/782 [==============================] - 1s 692us/step - loss: 1.0965 - acc: 0.6087 - val_loss: 1.3870 - val_acc: 0.4404
Epoch 242/1000
782/782 [==============================] - 1s 700us/step - loss: 1.1338 - acc: 0.5870 - val_loss: 1.3884 - val_acc: 0.4767
Epoch 243/1000
782/782 [==============================] - 1s 702us/step - loss: 1.0971 - acc: 0.5985 - val_loss: 1.3797 - val_acc: 0.4767
Epoch 244/1000
782/782 [==========

782/782 [==============================] - 1s 689us/step - loss: 0.8891 - acc: 0.6790 - val_loss: 1.3554 - val_acc: 0.5026
Epoch 356/1000
782/782 [==============================] - 1s 680us/step - loss: 0.8617 - acc: 0.6816 - val_loss: 1.3680 - val_acc: 0.5285
Epoch 357/1000
782/782 [==============================] - 1s 745us/step - loss: 0.8640 - acc: 0.7008 - val_loss: 1.3212 - val_acc: 0.5311
Epoch 358/1000
782/782 [==============================] - 1s 766us/step - loss: 0.8767 - acc: 0.7046 - val_loss: 1.3368 - val_acc: 0.5104
Epoch 359/1000
782/782 [==============================] - 1s 731us/step - loss: 0.9050 - acc: 0.6752 - val_loss: 1.3680 - val_acc: 0.5104
Epoch 360/1000
782/782 [==============================] - 1s 753us/step - loss: 0.8737 - acc: 0.6790 - val_loss: 1.3326 - val_acc: 0.5181
Epoch 361/1000
782/782 [==============================] - 1s 734us/step - loss: 0.8712 - acc: 0.6918 - val_loss: 1.3706 - val_acc: 0.4819
Epoch 362/1000
782/782 [=========================

782/782 [==============================] - 1s 670us/step - loss: 0.6853 - acc: 0.7647 - val_loss: 1.3484 - val_acc: 0.5544
Epoch 474/1000
782/782 [==============================] - 1s 718us/step - loss: 0.6628 - acc: 0.7775 - val_loss: 1.3494 - val_acc: 0.5440
Epoch 475/1000
782/782 [==============================] - 1s 723us/step - loss: 0.7163 - acc: 0.7545 - val_loss: 1.3507 - val_acc: 0.5725
Epoch 476/1000
782/782 [==============================] - 1s 710us/step - loss: 0.6580 - acc: 0.7852 - val_loss: 1.3289 - val_acc: 0.5337
Epoch 477/1000
782/782 [==============================] - 1s 715us/step - loss: 0.6951 - acc: 0.7570 - val_loss: 1.3160 - val_acc: 0.5466
Epoch 478/1000
782/782 [==============================] - 1s 722us/step - loss: 0.6528 - acc: 0.7903 - val_loss: 1.3488 - val_acc: 0.5518
Epoch 479/1000
782/782 [==============================] - 1s 708us/step - loss: 0.6700 - acc: 0.7737 - val_loss: 1.3693 - val_acc: 0.5415
Epoch 480/1000
782/782 [=========================

782/782 [==============================] - 1s 673us/step - loss: 0.5179 - acc: 0.8325 - val_loss: 1.4124 - val_acc: 0.5466
Epoch 592/1000
782/782 [==============================] - 1s 724us/step - loss: 0.5199 - acc: 0.8248 - val_loss: 1.4337 - val_acc: 0.5648
Epoch 593/1000
782/782 [==============================] - 1s 701us/step - loss: 0.5454 - acc: 0.8159 - val_loss: 1.4176 - val_acc: 0.5570
Epoch 594/1000
782/782 [==============================] - 1s 682us/step - loss: 0.5187 - acc: 0.8210 - val_loss: 1.4208 - val_acc: 0.5674
Epoch 595/1000
782/782 [==============================] - 1s 697us/step - loss: 0.5231 - acc: 0.8389 - val_loss: 1.3970 - val_acc: 0.5751
Epoch 596/1000
782/782 [==============================] - 1s 689us/step - loss: 0.5206 - acc: 0.8235 - val_loss: 1.3815 - val_acc: 0.5570
Epoch 597/1000
782/782 [==============================] - 1s 723us/step - loss: 0.5032 - acc: 0.8325 - val_loss: 1.4283 - val_acc: 0.5699
Epoch 598/1000
782/782 [=========================

782/782 [==============================] - 1s 705us/step - loss: 0.4209 - acc: 0.8632 - val_loss: 1.4881 - val_acc: 0.5751
Epoch 710/1000
782/782 [==============================] - 1s 742us/step - loss: 0.4005 - acc: 0.8581 - val_loss: 1.4722 - val_acc: 0.5881
Epoch 711/1000
782/782 [==============================] - 1s 737us/step - loss: 0.4183 - acc: 0.8606 - val_loss: 1.5012 - val_acc: 0.5751
Epoch 712/1000
782/782 [==============================] - 1s 721us/step - loss: 0.4071 - acc: 0.8593 - val_loss: 1.5057 - val_acc: 0.5674
Epoch 713/1000
782/782 [==============================] - 1s 730us/step - loss: 0.3780 - acc: 0.8747 - val_loss: 1.4913 - val_acc: 0.5622
Epoch 714/1000
782/782 [==============================] - 1s 703us/step - loss: 0.4202 - acc: 0.8581 - val_loss: 1.4448 - val_acc: 0.5544
Epoch 715/1000
782/782 [==============================] - 1s 737us/step - loss: 0.4121 - acc: 0.8645 - val_loss: 1.4511 - val_acc: 0.5829
Epoch 716/1000
782/782 [=========================

782/782 [==============================] - 1s 690us/step - loss: 0.2954 - acc: 0.9079 - val_loss: 1.5361 - val_acc: 0.5803
Epoch 828/1000
782/782 [==============================] - 1s 701us/step - loss: 0.3134 - acc: 0.8951 - val_loss: 1.5234 - val_acc: 0.5907
Epoch 829/1000
782/782 [==============================] - 1s 720us/step - loss: 0.3224 - acc: 0.8951 - val_loss: 1.5548 - val_acc: 0.5907
Epoch 830/1000
782/782 [==============================] - 1s 699us/step - loss: 0.3074 - acc: 0.9079 - val_loss: 1.5938 - val_acc: 0.5829
Epoch 831/1000
782/782 [==============================] - 1s 695us/step - loss: 0.3173 - acc: 0.9079 - val_loss: 1.5759 - val_acc: 0.5829
Epoch 832/1000
782/782 [==============================] - 1s 715us/step - loss: 0.3060 - acc: 0.8926 - val_loss: 1.5664 - val_acc: 0.5933
Epoch 833/1000
782/782 [==============================] - 1s 742us/step - loss: 0.3092 - acc: 0.8951 - val_loss: 1.5512 - val_acc: 0.5881
Epoch 834/1000
782/782 [=========================

782/782 [==============================] - 1s 675us/step - loss: 0.2456 - acc: 0.9258 - val_loss: 1.6549 - val_acc: 0.5984
Epoch 946/1000
782/782 [==============================] - 1s 705us/step - loss: 0.2602 - acc: 0.9143 - val_loss: 1.6543 - val_acc: 0.5881
Epoch 947/1000
782/782 [==============================] - 1s 715us/step - loss: 0.2180 - acc: 0.9386 - val_loss: 1.6900 - val_acc: 0.5881
Epoch 948/1000
782/782 [==============================] - 1s 698us/step - loss: 0.2564 - acc: 0.9309 - val_loss: 1.6416 - val_acc: 0.5984
Epoch 949/1000
782/782 [==============================] - 1s 716us/step - loss: 0.2107 - acc: 0.9412 - val_loss: 1.6701 - val_acc: 0.5907
Epoch 950/1000
782/782 [==============================] - 1s 680us/step - loss: 0.2393 - acc: 0.9258 - val_loss: 1.6315 - val_acc: 0.5959
Epoch 951/1000
782/782 [==============================] - 1s 708us/step - loss: 0.2288 - acc: 0.9284 - val_loss: 1.6129 - val_acc: 0.6010
Epoch 952/1000
782/782 [=========================

In [321]:

predictions = model.predict_classes(x_testcnn)

In [322]:
model_name = 'RAVDESS.h5'
save_dir = 'C:\\Users\\2304373\\Downloads\\to do python files\\'
# Save model and weights
if not os.path.isdir(save_dir):
    os.makedirs(save_dir)
model_path = os.path.join(save_dir, model_name)
model.save(model_path)
print('Saved trained model at %s ' % model_path)

Saved trained model at C:\Users\2304373\Downloads\to do python files\RAVDESS.h5 


In [323]:
predictions = model.predict_classes(x_testcnn)

In [324]:
predictions

array([4, 4, 0, 0, 6, 2, 4, 1, 1, 2, 0, 1, 5, 1, 3, 5, 2, 1, 3, 6, 2, 1,
       3, 2, 3, 2, 6, 4, 6, 3, 3, 4, 5, 4, 0, 1, 1, 4, 4, 2, 1, 4, 2, 6,
       1, 2, 5, 0, 2, 2, 1, 4, 2, 4, 5, 4, 3, 6, 3, 6, 2, 2, 1, 3, 0, 1,
       4, 6, 1, 3, 3, 2, 6, 4, 1, 5, 2, 2, 0, 4, 0, 6, 0, 2, 2, 0, 1, 1,
       1, 0, 3, 3, 1, 4, 3, 6, 3, 2, 2, 4, 2, 5, 2, 1, 4, 3, 6, 2, 1, 6,
       5, 3, 2, 6, 4, 1, 1, 6, 4, 3, 4, 2, 0, 2, 3, 4, 2, 1, 1, 1, 6, 5,
       3, 2, 6, 3, 6, 4, 0, 4, 2, 6, 4, 1, 3, 5, 3, 4, 4, 3, 1, 6, 4, 5,
       6, 6, 1, 2, 2, 6, 1, 4, 6, 2, 4, 0, 1, 4, 2, 3, 3, 4, 4, 5, 4, 6,
       0, 4, 5, 5, 1, 4, 2, 1, 6, 3, 3, 4, 1, 1, 3, 2, 0, 6, 6, 2, 3, 1,
       3, 2, 3, 6, 4, 5, 4, 0, 0, 6, 1, 1, 2, 3, 3, 1, 6, 6, 4, 1, 1, 4,
       1, 3, 2, 1, 3, 1, 3, 0, 1, 3, 6, 1, 6, 3, 6, 6, 4, 1, 4, 4, 1, 6,
       6, 0, 2, 6, 3, 6, 2, 6, 4, 3, 3, 4, 2, 2, 6, 3, 1, 0, 4, 5, 3, 2,
       5, 6, 2, 3, 6, 2, 0, 6, 4, 2, 3, 1, 2, 3, 1, 3, 2, 3, 6, 0, 0, 5,
       1, 0, 4, 4, 4, 3, 6, 4, 5, 3, 1, 4, 2, 3, 3,

In [325]:
import numpy as np
y_test = np.asarray(y_test)

In [326]:
new_Ytest = y_test.astype(int)

In [327]:
from sklearn.metrics import classification_report
report = classification_report(new_Ytest, predictions)
print(report)

              precision    recall  f1-score   support

           0       0.66      0.57      0.61        40
           1       0.63      0.74      0.68        58
           2       0.69      0.60      0.64        73
           3       0.57      0.59      0.58        63
           4       0.61      0.66      0.63        67
           5       0.48      0.30      0.37        33
           6       0.38      0.44      0.41        52

   micro avg       0.58      0.58      0.58       386
   macro avg       0.57      0.56      0.56       386
weighted avg       0.58      0.58      0.58       386



In [328]:
from sklearn.metrics import confusion_matrix
matrix = confusion_matrix(new_Ytest, predictions)
print (matrix)

[[23  0  5  2  9  1  0]
 [ 0 43  1  3  1  3  7]
 [ 3  4 44  5  5  2 10]
 [ 1  3  2 37  8  1 11]
 [ 6  1  1 10 44  1  4]
 [ 2 10  4  0  1 10  6]
 [ 0  7  7  8  4  3 23]]
